<?php

/*
|--------------------------------------------------------------------------
| Kalibrasyon Kapsamı ("/kapsam" sayfası verisi)
|--------------------------------------------------------------------------
|
| Her kategori: slug (filtre chip'i ile eşleşir), icon (emoji), title,
| summary (grup sayısı otomatik eklenir) ve groups[].
| Her grup: id (anchor + <details> id), title, columns[] ve rows[].
| rows[] içindeki hücre sayısı columns[] ile birebir olmalıdır.
| "—" değeri ön yüzde soluk (muted) gösterilir.
|
| Not: Değerler örnek kapsam tablolarıdır; laboratuvarın güncel TÜRKAK
| akreditasyon kapsamına göre admin/analist tarafından teyit edilmelidir.
|
*/

return [
    'note' => '<strong>U</strong> = Genişletilmiş ölçüm belirsizliği (k=2). <strong>Lab</strong> = Laboratuvarda, <strong>MY</strong> = Müşteri yerinde. Değerler kalibrasyon kapsamımıza göredir; cihaz ve parametreye göre değişebilir.',

    'categories' => [

        /* ============================ 1. SICAKLIK & NEM ============================ */
        [
            'slug' => 'sicaklik',
            'icon' => '🌡️',
            'title' => 'Sıcaklık & Nem',
            'summary' => 'Termometre, ısılçift, higrometre, etüv, fırın ve sıcaklık kaynakları',
            'groups' => [
                [
                    'id' => 'sicaklik-1',
                    'title' => 'Direnç Termometreleri (PRT, Endüstriyel PRT, Transmitter)',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C (Buz Noktası)', '—', '0.03 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.08 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.12 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['-90..0 °C', 'Blok Kalibratör', '0.10 °C', 'EN 60751, DKD R5-1', 'Lab'],
                        ['-35..150 °C', 'Blok Kalibratör', '0.12 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['50..400 °C', 'Blok Kalibratör', '0.20 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-2',
                    'title' => 'Isılçiftler (Endüstriyel Isılçiftler) - Karşılaştırma',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C', 'Buz Noktası', '0.10 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.16 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.33 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-90..0 °C', 'Blok Kalibratör', '0.19 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab'],
                        ['-35..150 °C', 'Blok Kalibratör', '0.25 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['50..400 °C', 'Blok Kalibratör', '0.50 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['400<T<=600 °C', 'Blok Kalibratör', '1.5 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['600<T<=1100 °C', 'Blok Kalibratör', '2.2 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-3',
                    'title' => 'Sıvılı Cam Termometreleri',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C', 'Buz Noktası', '0.03 °C', 'Karşılaştırma (0.05 °C bölüntülü üst)', 'Lab'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.09 °C', 'Karşılaştırma (0.05 °C bölüntülü üst)', 'Lab'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.12 °C', 'Karşılaştırma (0.05 °C bölüntülü üst)', 'Lab'],
                    ],
                ],
                [
                    'id' => 'sicaklik-4',
                    'title' => 'Göstergeli Sıcaklık Ölçerler - Termistör/Dirençli/Transmitter',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C', 'Buz Noktası', '0.03 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.08 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.12 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['-90..0 °C', 'Blok Kalibratör', '0.10 °C', 'EN 60751, DKD R5-1', 'Lab'],
                        ['-35..150 °C', 'Blok Kalibratör', '0.12 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['50..400 °C', 'Blok Kalibratör', '0.20 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-5',
                    'title' => 'Göstergeli Sıcaklık Ölçerler - Isılçift Sensör (Base Metal T,E,J,K,N)',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C', 'Buz Noktası', '0.26 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.28 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.40 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-90..0 °C', 'Blok Kalibratör', '0.28 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-35..150 °C', 'Blok Kalibratör', '0.40 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab'],
                        ['50..400 °C', 'Blok Kalibratör', '0.60 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['400<T<=600 °C', 'Blok Kalibratör', '1.5 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['600<T<=1100 °C', 'Blok Kalibratör', '3.0 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-6',
                    'title' => 'Göstergeli Sıcaklık Ölçerler - Isılçift Sensör (Asil Metal R,S)',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0 °C', 'Buz Noktası', '0.26 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-40..80 °C', 'Sıvı Banyo', '0.26 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıvı Banyo', '0.30 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['-50..0 °C', 'Blok Kalibratör', '0.26 °C', 'EN 60751, DKD R5-1', 'Lab'],
                        ['-35..150 °C', 'Blok Kalibratör', '0.40 °C', 'EN 60751, DKD R5-1', 'Lab/MY'],
                        ['50..400 °C', 'Blok Kalibratör', '0.40 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['400<T<=600 °C', 'Blok Kalibratör', '1.5 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                        ['600<T<=1100 °C', 'Blok Kalibratör', '2.2 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-7',
                    'title' => 'Göstergeli Sıcaklık Ölçerler - Isılçift Sensör (Asil Metal B Tipi)',
                    'columns' => ['Aralık', 'Ortam', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['600..1100 °C', 'Blok Kalibratör', '2.2 °C', 'EURAMET cg.8, EN 60584, DKD R5-3', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-8',
                    'title' => 'Bağıl Nem Ölçer (Kapasitif, Rezistif, Termograf, Mekanik, Islak/Kuru)',
                    'columns' => ['Ölçüm', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Bağıl Nem', '10-95 %rh, 15..35 °C', '2.0 %rh', 'DKD-R 5-8, Pt100 referans ile karşılaştırma', 'Lab'],
                        ['Bağıl Nem', '10-95 %rh, 15..35 °C', '1.5 %rh', 'DKD-R 5-8, psikrometrik sensör ile karşılaştırma', 'Lab'],
                    ],
                ],
                [
                    'id' => 'sicaklik-9',
                    'title' => 'Doğrulama Sıcaklık Ölçer',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['10..50 °C, 30-60 %rh', '0.20 °C', 'DKD-R 5-8, Pt100 referans', 'Lab'],
                        ['10..50 °C, 30-60 %rh', '0.17 °C', 'DKD-R 5-8, psikrometrik sensör', 'Lab'],
                    ],
                ],
                [
                    'id' => 'sicaklik-10',
                    'title' => 'Ortam Termometresi',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['50<T<=80 °C', '0.6 °C', 'DKD-R 5-8, dirençli sensör', 'Lab'],
                    ],
                ],
                [
                    'id' => 'sicaklik-11',
                    'title' => 'Sıcaklık Göstergesi (Elektriksel Simülasyon)',
                    'columns' => ['Tip', 'Eklem', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['B', 'ON', '600..1820 °C', '0.49 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['B', 'OFF', '600..1820 °C', '0.45 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['S', 'ON', '0..1767 °C', '0.49 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['S', 'OFF', '0..1767 °C', '0.45 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['R', 'ON', '0..1767 °C', '0.47 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['R', 'OFF', '0..1767 °C', '0.44 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['K', 'ON', '-200..1372 °C', '0.22 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['K', 'OFF', '-200..1372 °C', '0.21 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['N', 'ON', '-200..1300 °C', '0.21 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['N', 'OFF', '-200..1300 °C', '0.20 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['J', 'ON', '-210..1200 °C', '0.20 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['J', 'OFF', '-210..1200 °C', '0.19 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['T', 'ON', '-250..400 °C', '0.19 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['T', 'OFF', '-250..400 °C', '0.18 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['E', 'ON', '-250..1000 °C', '0.19 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['E', 'OFF', '-250..1000 °C', '0.18 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['Pt100', '—', '-200..850 °C', '0.05 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-12',
                    'title' => 'Sıcaklık Kalibratörü (Elektriksel Simülasyon)',
                    'columns' => ['Tip', 'Eklem', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['B', 'ON', '600..1820 °C', '0.34 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['B', 'OFF', '600..1820 °C', '0.28 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['S', 'ON', '0..1767 °C', '0.34 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['S', 'OFF', '0..1767 °C', '0.27 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['R', 'ON', '0..1767 °C', '0.29 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['R', 'OFF', '0..1767 °C', '0.24 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['K', 'ON', '-200..1372 °C', '0.15 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['K', 'OFF', '-200..1372 °C', '0.13 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['N', 'ON', '-200..1300 °C', '0.13 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['N', 'OFF', '-200..1300 °C', '0.11 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['J', 'ON', '-210..1200 °C', '0.11 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['J', 'OFF', '-210..1200 °C', '0.10 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['T', 'ON', '-250..400 °C', '0.10 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['T', 'OFF', '-250..400 °C', '0.09 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['E', 'ON', '-250..1000 °C', '0.09 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['E', 'OFF', '-250..1000 °C', '0.09 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['Pt100', '—', '-200..<0 °C', '0.02 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                        ['Pt100', '—', '0..650 °C', '0.05 °C', 'EURAMET cg.11, elektriksel sim.', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-13',
                    'title' => 'Etüv / Sterilizatör / İnkübatör / Fırın / Soğuk Oda / Buz Dolabı / Klimatik Kabin',
                    'columns' => ['Aralık', 'Ölçüm', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['-90..80 °C', 'Sıcaklık Dağılımı', '0.70 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['80<T<=140 °C', 'Sıcaklık Dağılımı', '1.0 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['140<T<=200 °C', 'Sıcaklık Dağılımı', '1.4 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['200<T<=250 °C', 'Sıcaklık Dağılımı', '1.8 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['-90..80 °C', 'Noktasal Sıcaklık', '0.50 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['80<T<=140 °C', 'Noktasal Sıcaklık', '0.70 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['140<T<=200 °C', 'Noktasal Sıcaklık', '0.90 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['200<T<=250 °C', 'Noktasal Sıcaklık', '1.1 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. ısılçift', 'Lab/MY'],
                        ['-90..80 °C', 'Sıcaklık Dağılımı', '0.50 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. dirençli', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıcaklık Dağılımı', '0.70 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. dirençli', 'Lab/MY'],
                        ['-90..400 °C', 'Noktasal Sıcaklık', '0.20 °C', 'EURAMET cg.20, DKD-R 5-7, EN 60068-3-5, ref. dirençli', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-14',
                    'title' => 'İklimlendirme Kabini (Bağıl Nem Dağılımı)',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['10-90 %rh, 15..35 °C', '3.0 %rh', 'EURAMET cg.20, kapasitif sensör', 'Lab/MY'],
                        ['10-95 %rh, 5..85 °C', '2.0 %rh', 'EURAMET cg.20, psikrometrik sensör', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-15',
                    'title' => 'Otoklav / Buhar Sterilizatörü / Vakumlu Etüv',
                    'columns' => ['Ölçüm', 'U', 'Yer'],
                    'rows' => [
                        ['Sıcaklık (30..140 °C)', '0.3 °C', 'Lab/MY'],
                        ['Basınç (30..140 °C)', '0.042 bar', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-16',
                    'title' => 'Kül Fırını',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['100..1400 °C, eksenel dağılım', '4.5 °C', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-17',
                    'title' => 'Sıvı Banyo',
                    'columns' => ['Aralık', 'Ölçüm', 'U', 'Referans', 'Yer'],
                    'rows' => [
                        ['-90..80 °C', 'Sıcaklık Dağılımı', '0.15 °C', 'Dirençli sens.', 'Lab/MY'],
                        ['80<T<=250 °C', 'Sıcaklık Dağılımı', '0.22 °C', 'Dirençli sens.', 'Lab/MY'],
                        ['-90..80 °C', 'Noktasal Sıcaklık', '0.05 °C', 'Dirençli sens.', 'Lab/MY'],
                        ['80<T<=250 °C', 'Noktasal Sıcaklık', '0.08 °C', 'Dirençli sens.', 'Lab/MY'],
                        ['250<T<=400 °C', 'Noktasal Sıcaklık', '0.12 °C', 'Dirençli sens.', 'Lab/MY'],
                        ['-90..80 °C', 'Sıcaklık Dağılımı', '0.50 °C', 'Isılçift sens.', 'Lab/MY'],
                        ['80<T<=140 °C', 'Sıcaklık Dağılımı', '0.60 °C', 'Isılçift sens.', 'Lab/MY'],
                        ['140<T<=200 °C', 'Sıcaklık Dağılımı', '0.70 °C', 'Isılçift sens.', 'Lab/MY'],
                        ['200<T<=250 °C', 'Sıcaklık Dağılımı', '0.80 °C', 'Isılçift sens.', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-18',
                    'title' => 'Sıcak Yüzey (Hot Plate)',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['20..50 °C', '1.0 °C', 'Lab/MY'],
                        ['50<T<=100 °C', '1.3 °C', 'Lab/MY'],
                        ['100<T<=150 °C', '1.5 °C', 'Lab/MY'],
                        ['150<T<=200 °C', '2.0 °C', 'Lab/MY'],
                        ['200<T<=250 °C', '2.5 °C', 'Lab/MY'],
                        ['250<T<=400 °C', '5.0 °C', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-19',
                    'title' => 'Kuru Blok Kalibratörleri',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['-90..400 °C', '0.4 °C', 'EURAMET cg.13, karşılaştırma', 'Lab/MY'],
                        ['400<T<=1100 °C', '2.3 °C', 'EURAMET cg.13, karşılaştırma', 'Lab/MY'],
                        ['1100<T<=1400 °C', '4.5 °C', 'EURAMET cg.13, karşılaştırma', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-20',
                    'title' => 'Endüstriyel Radyasyon Termometreleri (Pirometre / IR)',
                    'columns' => ['Aralık', 'Kaynak', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['20..250 °C', 'IR Kalibratör', '2.1 °C', 'ASTM E2847, karşılaştırma', 'Lab/MY'],
                        ['250<T<=400 °C', 'IR Kalibratör', '3.2 °C', 'ASTM E2847, karşılaştırma', 'Lab/MY'],
                        ['50..600 °C', 'IR Kalibratör (kaviteli)', '3.2 °C', 'ASTM E2847, karşılaştırma', 'Lab/MY'],
                        ['600<T<=1000 °C', 'IR Kalibratör (kaviteli)', '6.0 °C', 'ASTM E2847, karşılaştırma', 'Lab/MY'],
                        ['1000<T<=1200 °C', 'IR Kalibratör (kaviteli)', '7.5 °C', 'ASTM E2847, karşılaştırma', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sicaklik-21',
                    'title' => 'Yüzey Sıcaklık Termometreleri',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['20..50 °C', '0.5 °C', 'Karşılaştırma, yüzey kalibratörü', 'Lab/MY'],
                        ['50<T<=100 °C', '0.8 °C', 'Karşılaştırma, yüzey kalibratörü', 'Lab/MY'],
                        ['100<T<=150 °C', '1.1 °C', 'Karşılaştırma, yüzey kalibratörü', 'Lab/MY'],
                        ['150<T<=200 °C', '1.4 °C', 'Karşılaştırma, yüzey kalibratörü', 'Lab/MY'],
                        ['200<T<=250 °C', '1.7 °C', 'Karşılaştırma, yüzey kalibratörü', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ============================ 2. BOYUTSAL ÖLÇÜMLER ============================ */
        [
            'slug' => 'boyut',
            'icon' => '📐',
            'title' => 'Boyutsal Ölçümler',
            'summary' => 'Kumpas, mikrometre, mastar, çap, açı ve yüzey pürüzlülüğü',
            'groups' => [
                [
                    'id' => 'boyut-1',
                    'title' => 'Uzunluk - 1 Boyut Ölçme',
                    'columns' => ['Cihaz', 'Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Mikrometre / Kumpas (1-D)', '0-100 mm', '0.05 µm', '(0.5+0.7L) µm', 'VDI/VDE/DGQ 2618 B.14.1, 1-D ile', 'Lab'],
                        ['Aynısı (Lazer)', '0-100 mm', '0.05 µm', '(0.14+1.0L) µm', 'VDI/VDE/DGQ 2618 B.14.1, lazer', 'Lab'],
                        ['Mastar Blok Komparatörü', '0.5-100 mm', '0.01 µm', '33 nm', 'EURAMET cg.02', 'MY'],
                        ['1-D Ölçü Cihazı (üniversal)', '0-300 mm', '0.01 µm', '(0.2+2L) µm', 'VDI/VDE/DGQ 2618 B.17.1', 'MY'],
                        ['Ölçü Saati Test', '0-25 mm', '0.001 mm', '0.8 µm', 'VDI/VDE/DGQ 2618 B.10.4', 'Lab/MY'],
                        ['Ölçü Saati Test (Lazer)', '0-100 mm', '0.01 µm', '(0.10+1.0L) µm', 'VDI/VDE/DGQ 2618 B.17.2', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'boyut-2',
                    'title' => 'El Tipi Temel Ölçü Cihazları',
                    'columns' => ['Cihaz', 'Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Mikrometre Kafası', '0-25 mm', '0.001 mm', '0.8 µm', 'VDI 2618 B.10.4', 'Lab'],
                        ['Dış Silindir (Tampon)', '0.2-300 mm', '—', '(0.7+2.4D) µm', 'VDI 2618 B.4.1', 'Lab'],
                        ['Pim / Tel', '0.1-20 mm', '—', '0.4 µm', 'VDI 2618 B.4.2', 'Lab'],
                        ['İç Silindir (Halka)', '0.7-200 mm', '—', '(0.6+2.5D) µm', 'VDI 2618 B.4.1', 'Lab'],
                        ['Küre / T-Probu', '0.3-100 mm', '—', '(0.4+4.6D) µm', 'Karşılaştırma', 'Lab'],
                        ['Dış Çap Mikrometresi', '0-2000 mm', '0.001 mm', '(1.3+25L) µm', 'VDI 2618 B.10.1', 'Lab'],
                        ['Derinlik Mikrometresi', '0-300 mm', '0.001 mm', '(1.0+10L) µm', 'VDI 2618 B.10.5', 'Lab'],
                        ['2 Noktalı İç Çap Mik.', '0-300 mm', '0.001 mm', '(1.0+10L) µm', 'VDI 2618 B.10.7', 'Lab'],
                        ['3 Noktalı İç Çap Mik.', '0-100 mm', '0.001 mm', '(1.2+20L) µm', 'VDI 2618 B.10.8', 'Lab'],
                        ['Kumpas (dış/iç/derinlik)', '0-300 mm', '0.005 mm', '(6+20L) µm', 'VDI 2618 B.9.1', 'Lab'],
                        ['Kumpas (300-3000 mm)', '300-3000 mm', '0.01 mm', '(15+32L) µm', 'VDI 2618 B.9.1', 'Lab'],
                        ['Derinlik Kumpası (0-200)', '0-200 mm', '0.005 mm', '(7+15L) µm', 'VDI 2618 B.9.2', 'Lab'],
                        ['Derinlik Kumpası (200-1000)', '200-1000 mm', '0.01 mm', '(13+25L) µm', 'VDI 2618 B.9.2', 'Lab'],
                        ['Mihengir', '0-1000 mm', '0.01 mm', '(13+25L) µm', 'VDI 2618 B.9.3', 'Lab'],
                        ['Ölçü Saati (analog)', '0-10 mm', '0.001 mm', '1.0 µm', 'VDI 2618 B.11.1', 'Lab'],
                        ['Ölçü Saati (analog)', '0-100 mm', '0.01 mm', '(2+3L) µm', 'VDI 2618 B.11.1', 'Lab'],
                        ['Ölçü Saati (dijital)', '0-100 mm', '0.5 µm', '(0.7+6L) µm', 'VDI 2618 B.11.4', 'Lab'],
                        ['Salgı Komparatörü', '0-2 mm', '0.001 mm', '0.7 µm', 'VDI 2618 B.11.3', 'Lab'],
                        ['Endikatör', '0-1 mm', '0.001 mm', '0.6 µm', 'VDI 2618 B.11.2', 'Lab'],
                        ['Üçlü Mastar (dış/iç)', 'D<=250 mm', '—', '(0.6+2.5D) µm', 'VDI 2618 B.4.7', 'Lab'],
                        ['Delik Mastarı (bore gauge)', '0-300 mm', '0.001 mm', '(1.5+10L) µm', 'VDI 2618 B.13.2', 'Lab'],
                        ['Kalınlık Ölçer (0-50)', '0-50 mm', '0.001 mm', '1.9 µm', 'Paralel blok ile', 'Lab'],
                        ['Pasometre', '0-2 mm', '0.001 mm', '0.7 µm', 'VDI 2618 B.10.3', 'Lab'],
                        ['Kalınlık (dış kollu)', '0-200 mm', '0.001 mm', '3.0 µm', 'VDI 2618 B.12.1', 'Lab'],
                        ['Kalınlık (iç kollu)', '0-100 mm', '0.001 mm', '3.0 µm', 'VDI 2618 B.13.1', 'Lab'],
                        ['Aplikatör', 'L<=2 mm', '—', '0.6 µm', 'ASTM D823, D4400', 'Lab'],
                        ['Grindometre', 'L<=100 µm', '—', '0.6 µm', 'ISO 1524, ASTM D1210', 'Lab'],
                        ['Yaş Film Tarağı', 'L<=5 mm', '—', '2.0 µm', 'ISO 2808, ASTM D4414', 'Lab'],
                        ['Cross-Cut (kot)', 'L<=10 mm', '—', '6.0 µm', 'ISO 2409', 'Lab'],
                        ['Cross-Cut (açı)', 'L<=10 mm', '—', "10'", 'ISO 2409', 'Lab'],
                        ['Ultrasonik Kalınlık', '0-100 mm', '0.001 mm', '(5.0+30L) µm', 'Karşılaştırma', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-3',
                    'title' => 'Boyut Standartları',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Açıklama', 'Yer'],
                    'rows' => [
                        ['Mastar Bloku (çelik)', '0.5-100 mm', '(0.07+0.5L) µm', '1-D, merkez nokta sapma', 'Lab'],
                        ['Mastar Bloku (seramik)', '0.5-100 mm', '(0.07+0.6L) µm', '1-D, merkez nokta sapma', 'Lab'],
                        ['Mastar Bloku (tungsten)', '0.5-100 mm', '(0.07+1.3L) µm', '1-D, merkez nokta sapma', 'Lab'],
                        ['Mastar Bloku Sapma', '0.5-100 mm', '0.05 µm', 'Sapma aralığı', 'Lab'],
                        ['Uzun Mastar (çelik)', '100-300 mm', '(0.15+1.5L) µm', '1-D', 'Lab'],
                        ['Uzun Mastar (seramik)', '100-300 mm', '(0.15+1.7L) µm', '1-D', 'Lab'],
                        ['Uzun Mastar (tungsten)', '100-300 mm', '(0.15+4L) µm', '1-D', 'Lab'],
                        ['Mikrometre Ayar Çubuğu', '25-300 mm', '(0.4+3L) µm', '1-D, merkez nokta', 'Lab'],
                        ['Kalınlık Mastarı', '10 µm-2 mm', '0.7 µm', '1-D, 3 nokta', 'Lab'],
                        ['Mastar Bloku (<0.5 mm)', '<0.5 mm', '0.18 µm', '1-D, tüm tipler', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-4',
                    'title' => 'Çizgi Standartları',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Hassas Çizgi Skalası', '0-10 mm', '0.5 µm', 'Optik, referans cam cetvel', 'Lab'],
                        ['Hassas Çizgi Skalası', '10-300 mm', '(0.6+2.7L) µm', 'Optik, referans cam cetvel', 'Lab'],
                        ['Hassas Çizgi Skalası', '0-300 mm', '(0.4+1.1L) µm', 'Lazer interferometre', 'Lab'],
                        ['Çelik Cetvel / Mekanik Sk.', '0-300 mm', '0.05 mm', '2-D ile optik', 'Lab'],
                        ['Çelik Cetvel', '0-3 m', '(200+30L) µm', 'Mastar cetvel', 'Lab'],
                        ['Şerit Metre (0-3 m)', '0-3 m', '(200+38L) µm', 'Mastar cetvel', 'Lab'],
                        ['Şerit Metre (3-50 m)', '3-50 m', '(200+75L) µm', 'Mastar cetvel', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-5',
                    'title' => 'Çap Standartları',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Dış Silindir', '0.2-300 mm', '(0.7+2.4D) µm', '1-D, dış çap', 'Lab'],
                        ['Pim / Tel', '0.1-20 mm', '0.4 µm', '1-D, dış çap', 'Lab'],
                        ['İç Silindir (Halka)', '0.7-200 mm', '(0.6+2.5D) µm', '1-D, iç çap', 'Lab'],
                        ['Küre / T-Probu', '0.3-100 mm', '(0.4+4.6D) µm', '1-D, çap', 'Lab'],
                        ['Konik Tampon', 'D<200 mm', '2.0 µm', '1-D, dış çap', 'Lab'],
                        ['Konik Halka', 'D<200 mm', '2.0 µm', '1-D, iç çap', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-6',
                    'title' => 'Açı Ölçme',
                    'columns' => ['Cihaz', 'Aralık', 'r', 'U', 'Yer'],
                    'rows' => [
                        ['Protaktör', '360°', "30'", "0.4'", 'Lab'],
                        ['Protaktör Taban (L>1000)', 'L>1000 mm', '—', 'Paralellik 3.0 µm, doğrusallık 2.0 µm', 'Lab'],
                        ['Klinometre', '90°', '0.001°', '0.0012°', 'Lab'],
                        ['Klinometre Taban', 'L>200 mm', '0.001 mm/m', '3.5 µm/m', 'Lab'],
                        ['Elektronik Seviye (L>200)', 'L>200 mm', '0.02 mm/m', '6 µm/m', 'Lab'],
                        ['Elektronik Seviye (L>1000)', 'L>1000 mm', '0.5 mm/m', '0.3 mm/m', 'Lab'],
                        ['Elektronik Seviye Paralel.', 'L>1000 mm', '—', '3.0 µm', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-7',
                    'title' => 'Düzlemsellik',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Optik Flat (paralellik)', '0-100 mm', '0.08 µm', 'Merkezi kalınlık', 'Lab'],
                        ['Optik Flat (düzlemsellik)', '60-100 mm', '0.4 µm', 'Referans cam mastar', 'Lab'],
                        ['Optik Flat (düzlemsellik)', '0-60 mm', '0.2 µm', 'Mastar komparatör', 'Lab'],
                        ['Pleyt', 'L<=8 m', '(0.6+0.004F) µm', 'Lazer interferometre', 'MY'],
                    ],
                ],
                [
                    'id' => 'boyut-8',
                    'title' => 'Vida Standartları',
                    'columns' => ['Cihaz', 'Adım', 'U', 'Yer'],
                    'rows' => [
                        ['Düz Vida Tampon (D>300)', '0.5-6 mm', '2.5 µm', 'Lab'],
                        ['Düz Vida Halka (D>200)', '0.5-6 mm', '2.7 µm', 'Lab'],
                        ['Konik Vida Tampon (D>300)', '0.5-6 mm', '3.0 µm', 'Lab'],
                        ['Konik Vida Halka (D>200)', '0.5-6 mm', '2.7 µm', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-9',
                    'title' => 'Vida Diş Tarakları',
                    'columns' => ['Ölçüm', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Adım', '<=10 mm', '10.0 µm', 'Optik, direkt', 'Lab'],
                        ['Açı', '<=10 mm', "15'", 'Optik, direkt', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-10',
                    'title' => '2 Boyut / 3 Boyut Ölçme',
                    'columns' => ['Cihaz', 'Eksen', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Projeksiyon / Mikroskop', 'X-Y', '<=10 mm', '0.5 µm (cetvel), 0.2 µm (lazer)', 'Karşılaştırma', 'MY'],
                        ['Projeksiyon / Mikroskop', 'X-Y', '10-300 mm', '(0.7+4L) µm, (0.2+1L) µm', 'Karşılaştırma', 'MY'],
                        ['Projeksiyon / Mikroskop', 'Açı', '360°', "0.3'", 'Açı mastar blokları', 'MY'],
                        ['Projeksiyon / Mikroskop', 'Büyütme', '5X-100X', '%1-%0.3', 'Karşılaştırma', 'MY'],
                        ['CMM', 'X-Y-Z', '0-10 m', '(0.6+1.8L) µm', 'VDI 2618 B.17.2, EN ISO 10360', 'MY'],
                        ['Tek Eksen Lineer', '—', '0-10 m', '(0.8+1.8L) µm', 'VDI 2618 B.17.2, lazer', 'MY'],
                        ['1-D Üniversal', '—', '0-1000 mm', '(0.1+0.5L) µm', 'VDI 2618 B.17.1/17.2, lazer', 'MY'],
                    ],
                ],
                [
                    'id' => 'boyut-11',
                    'title' => 'Yüzey Pürüzlülüğü',
                    'columns' => ['Parametre', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Ra', '0.4-3 µm', '(23+33Ra) nm', 'DKD-R 4.2 B.1, pürüzlülük standardı', 'Lab'],
                        ['Rz', '1.6-11.5 µm', '(84+32Rz) nm', 'DKD-R 4.2 B.1, pürüzlülük standardı', 'Lab'],
                    ],
                ],
                [
                    'id' => 'boyut-12',
                    'title' => 'Diğer Boyutsal',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Lazer Mesafe', '0-20 m', '(2.0+0.16L) mm', 'Referans lazer, karşılaştırma', 'Lab/MY'],
                        ['Yarı Çap / Abalon', 'D>50 mm', '2.3 µm', '2-D, optik', 'Lab'],
                        ['Açı Abalonları', '360°', "0.4'", '2-D, optik', 'Lab'],
                        ['Kaynakçı Kumpası (yükseklik)', '0-50 mm', '0.012 mm', 'Blok mastar, karşılaştırma', 'Lab'],
                        ['Kaynakçı Kumpası (aralık)', '0-100 mm', '0.02 mm', 'Optik, karşılaştırma', 'Lab'],
                        ['Kaynakçı Kumpası (açı)', '90°', '0.02°', 'Optik, karşılaştırma', 'Lab'],
                        ['Pah Kumpası', '0-50 mm', '0.012 mm', 'Optik, karşılaştırma', 'Lab'],
                        ['Kaplama Kalınlığı Standardı', '10 µm-50 mm', '(0.5+30L) µm', '1-D, 5 nokta', 'Lab'],
                        ['Kaplama Kalınlığı Ölçer', '0-2 mm', '0.8 µm', 'Kalınlık folyosu', 'Lab'],
                        ['Test Elekleri (20 µm-5 mm)', '20 µm-5 mm', '(0.9+6.5L) µm', '2-D', 'Lab'],
                        ['Test Elekleri (5-125 mm)', '5-125 mm', '(40+2.6L) µm', 'Dijital kumpas', 'Lab'],
                        ['Beton Kalıp Paralellik', '35-300 mm', '0.03 mm', 'TS 12390-1, ASTM', 'Lab/MY'],
                        ['Beton Kalıp Diklik', '35-300 mm', '0.05 mm', 'TS 12390-1, ASTM', 'Lab/MY'],
                        ['Beton Kalıp Doğrusallık', '35-300 mm', '0.01 mm', 'TS 12390-1, ASTM', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ============================ 3. BASINÇ ============================ */
        [
            'slug' => 'basinc',
            'icon' => '🧭',
            'title' => 'Basınç',
            'summary' => 'Manometre, transmitter, DWT; bağıl, mutlak ve fark basınç',
            'groups' => [
                [
                    'id' => 'basinc-1',
                    'title' => 'Bağıl Basınç - Pistonlu Standart (DWT)',
                    'columns' => ['Cihaz', 'Aralık', 'Tür', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['DWT', '0.1-4 MPa', 'Pnömatik', '3 Pa + 1.07E-4·p', 'EURAMET cg.3', 'Lab'],
                        ['DWT', '0.1-6 MPa', 'Hidrolik', '5 Pa + 5.45E-5·p', 'EURAMET cg.3', 'Lab'],
                        ['DWT', '6-120 MPa', 'Hidrolik', '122 Pa + 8.79E-5·p', 'EURAMET cg.3', 'Lab'],
                    ],
                ],
                [
                    'id' => 'basinc-2',
                    'title' => 'Bağıl Basınç - Manometre / Transmitter / Kalibratör',
                    'columns' => ['Aralık', 'Tür', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['1-40 bar', 'Pnömatik (DWT)', '9.6E-5 bar + 7.6E-5·p', 'EURAMET cg.17', 'Lab'],
                        ['1-60 bar', 'Hidrolik (DWT)', '1.2E-4 bar + 2.4E-5·p', 'EURAMET cg.17', 'Lab'],
                        ['60-1200 bar', 'Hidrolik (DWT)', '2.2E-3 bar + 5.4E-5·p', 'EURAMET cg.17', 'Lab'],
                        ['-0.9..-0.04 bar', 'Pnömatik', '1.3E-4 bar + 3.7E-4·p', 'EURAMET cg.17', 'Lab/MY'],
                        ['0.015-1 bar', 'Pnömatik', '1.3E-4 bar + 3.7E-4·p', 'EURAMET cg.17', 'Lab/MY'],
                        ['-0.9..2 bar', 'Pnömatik', '0.63 mbar', 'EURAMET cg.17', 'Lab/MY'],
                        ['2-25 bar', 'Pnömatik', '1.8E-2 bar + 4E-4·p', 'EURAMET cg.17', 'Lab/MY'],
                        ['10-400 bar', 'Hidrolik', '6.3E-2 bar + 5E-4·p', 'EURAMET cg.17', 'Lab/MY'],
                        ['400-700 bar', 'Hidrolik', '2.6E-1 bar + 3E-4·p', 'EURAMET cg.17', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'basinc-3',
                    'title' => 'Fark Basıncı',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['-2000..-10 Pa', '3.1 Pa', 'Lab/MY'],
                        ['10-2000 Pa', '3.1 Pa', 'Lab/MY'],
                        ['-10000..-2001 Pa', '8.1 Pa', 'Lab/MY'],
                        ['2001-10000 Pa', '8.1 Pa', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'basinc-4',
                    'title' => 'Mutlak Basınç',
                    'columns' => ['Aralık', 'Tür', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['750-1100 hPa', 'Pnömatik', '0.4 hPa', 'EURAMET cg.17', 'Lab'],
                        ['1-41 bar', 'Pnömatik (DWT)', '9.6E-5 bar + 7.5E-5·pabs', 'EURAMET cg.17', 'Lab'],
                        ['1-61 bar', 'Pnömatik (DWT)', '1.2E-4 bar + 2.4E-5·pabs', 'EURAMET cg.17', 'Lab'],
                        ['61-1201 bar', 'Hidrolik (DWT)', '2.2E-3 bar + 5.4E-5·pabs', 'EURAMET cg.17', 'Lab'],
                        ['0.015-3 bar', 'Pnömatik', '0.6 mbar', 'EURAMET cg.17', 'Lab/MY'],
                        ['2-26 bar', 'Pnömatik', '1.8E-2 bar + 4E-4·pabs', 'EURAMET cg.17', 'Lab/MY'],
                        ['10-401 bar', 'Hidrolik', '6.4E-2 bar + 5E-4·pabs', 'EURAMET cg.17', 'Lab/MY'],
                        ['401-701 bar', 'Hidrolik', '2.7E-1 bar + 3E-4·pabs', 'EURAMET cg.17', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ============================ 4. KÜTLE & TARTI ============================ */
        [
            'slug' => 'kutle',
            'icon' => '⚖️',
            'title' => 'Kütle & Tartı',
            'summary' => 'E2–M3 sınıfı kütle standartları ve tartı aletleri',
            'groups' => [
                [
                    'id' => 'kutle-1',
                    'title' => 'Tartı Aletleri (Otomatik Olmayan)',
                    'columns' => ['Cihaz', 'Aralık', 'Referans', 'U', 'Açıklama', 'Yer'],
                    'rows' => [
                        ['Terazi', 'm<=10 kg', 'E2 kütle', '1E-6', 'm = kapasite', 'MY'],
                        ['Terazi', 'm>40 kg', 'F1 kütle', '5.3E-6', 'm = kapasite', 'MY'],
                        ['Terazi', 'm<=1000 kg', 'M1 kütle', '9.4E-5', 'm = kapasite', 'MY'],
                        ['Terazi', '1000<m<=2000 kg', 'M1 + ikame', '1.2E-4', 'm = kapasite', 'MY'],
                        ['Terazi', '1 mg<=m<=20 mg', 'E1 kütle', '2.5 µg', 'm = tartım', 'MY'],
                    ],
                ],
                [
                    'id' => 'kutle-2',
                    'title' => 'E2 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['1 mg-20 mg', '0.003 mg', 'OIML R-111', 'Lab'],
                        ['50 mg', '0.004 mg', 'OIML R-111', 'Lab'],
                        ['100 mg', '0.005 mg', 'OIML R-111', 'Lab'],
                        ['200 mg', '0.006 mg', 'OIML R-111', 'Lab'],
                        ['500 mg', '0.008 mg', 'OIML R-111', 'Lab'],
                        ['1 g', '0.010 mg', 'OIML R-111', 'Lab'],
                        ['2 g', '0.012 mg', 'OIML R-111', 'Lab'],
                        ['5 g', '0.016 mg', 'OIML R-111', 'Lab'],
                        ['10 g', '0.020 mg', 'OIML R-111', 'Lab'],
                        ['20 g', '0.025 mg', 'OIML R-111', 'Lab'],
                        ['50 g', '0.03 mg', 'OIML R-111', 'Lab'],
                        ['100 g', '0.05 mg', 'OIML R-111', 'Lab'],
                        ['200 g', '0.10 mg', 'OIML R-111', 'Lab'],
                        ['500 g', '0.25 mg', 'OIML R-111', 'Lab'],
                        ['1 kg', '0.50 mg', 'OIML R-111', 'Lab'],
                        ['2 kg', '1.0 mg', 'OIML R-111', 'Lab'],
                        ['5 kg', '2.5 mg', 'OIML R-111', 'Lab'],
                    ],
                ],
                [
                    'id' => 'kutle-3',
                    'title' => 'F1 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1 mg-5 mg', '0.006 mg', 'Lab'],
                        ['10 mg', '0.008 mg', 'Lab'],
                        ['20 mg', '0.010 mg', 'Lab'],
                        ['50 mg', '0.012 mg', 'Lab'],
                        ['100 mg', '0.016 mg', 'Lab'],
                        ['200 mg', '0.020 mg', 'Lab'],
                        ['500 mg', '0.025 mg', 'Lab'],
                        ['1 g', '0.03 mg', 'Lab'],
                        ['2 g', '0.04 mg', 'Lab'],
                        ['5 g', '0.05 mg', 'Lab'],
                        ['10 g', '0.06 mg', 'Lab'],
                        ['20 g', '0.08 mg', 'Lab'],
                        ['50 g', '0.10 mg', 'Lab'],
                        ['100 g', '0.16 mg', 'Lab'],
                        ['200 g', '0.30 mg', 'Lab'],
                        ['500 g', '0.80 mg', 'Lab'],
                        ['1 kg', '1.6 mg', 'Lab'],
                        ['2 kg', '3.0 mg', 'Lab'],
                        ['5 kg', '8.0 mg', 'Lab'],
                        ['10 kg', '16 mg', 'Lab'],
                        ['20 kg', '30 mg', 'Lab'],
                        ['50 kg', '80 mg', 'Lab'],
                    ],
                ],
                [
                    'id' => 'kutle-4',
                    'title' => 'F2 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1 mg-5 mg', '0.020 mg', 'Lab'],
                        ['10 mg', '0.025 mg', 'Lab'],
                        ['20 mg', '0.03 mg', 'Lab'],
                        ['50 mg', '0.04 mg', 'Lab'],
                        ['100 mg', '0.05 mg', 'Lab'],
                        ['200 mg', '0.06 mg', 'Lab'],
                        ['500 mg', '0.08 mg', 'Lab'],
                        ['1 g', '0.10 mg', 'Lab'],
                        ['2 g', '0.12 mg', 'Lab'],
                        ['5 g', '0.16 mg', 'Lab'],
                        ['10 g', '0.20 mg', 'Lab'],
                        ['20 g', '0.25 mg', 'Lab'],
                        ['50 g', '0.30 mg', 'Lab'],
                        ['100 g', '0.50 mg', 'Lab'],
                        ['200 g', '1.0 mg', 'Lab'],
                        ['500 g', '2.5 mg', 'Lab'],
                        ['1 kg', '5.0 mg', 'Lab'],
                        ['2 kg', '10 mg', 'Lab'],
                        ['5 kg', '25 mg', 'Lab'],
                        ['10 kg', '50 mg', 'Lab'],
                        ['20 kg', '100 mg', 'Lab'],
                        ['50 kg', '250 mg', 'Lab'],
                    ],
                ],
                [
                    'id' => 'kutle-5',
                    'title' => 'M1 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1 mg-5 mg', '0.06 mg', 'Lab'],
                        ['10 mg', '0.08 mg', 'Lab'],
                        ['20 mg', '0.10 mg', 'Lab'],
                        ['50 mg', '0.12 mg', 'Lab'],
                        ['100 mg', '0.16 mg', 'Lab'],
                        ['200 mg', '0.20 mg', 'Lab'],
                        ['500 mg', '0.25 mg', 'Lab'],
                        ['1 g', '0.30 mg', 'Lab'],
                        ['2 g', '0.40 mg', 'Lab'],
                        ['5 g', '0.50 mg', 'Lab'],
                        ['10 g', '0.60 mg', 'Lab'],
                        ['20 g', '0.80 mg', 'Lab'],
                        ['50 g', '1.0 mg', 'Lab'],
                        ['100 g', '1.6 mg', 'Lab'],
                        ['200 g', '3.0 mg', 'Lab'],
                        ['500 g', '8.0 mg', 'Lab'],
                        ['1 kg', '16 mg', 'Lab'],
                        ['2 kg', '30 mg', 'Lab'],
                        ['5 kg', '80 mg', 'Lab'],
                        ['10 kg', '160 mg', 'Lab/MY'],
                        ['20 kg', '300 mg', 'Lab/MY'],
                        ['50 kg', '800 mg', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'kutle-6',
                    'title' => 'M2 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['100 mg', '0.50 mg', 'Lab'],
                        ['200 mg', '0.60 mg', 'Lab'],
                        ['500 mg', '0.80 mg', 'Lab'],
                        ['1 g', '1.0 mg', 'Lab'],
                        ['2 g', '1.2 mg', 'Lab'],
                        ['5 g', '1.6 mg', 'Lab'],
                        ['10 g', '2.0 mg', 'Lab'],
                        ['20 g', '2.5 mg', 'Lab'],
                        ['50 g', '3.0 mg', 'Lab'],
                        ['100 g', '5.0 mg', 'Lab'],
                        ['200 g', '10 mg', 'Lab'],
                        ['500 g', '25 mg', 'Lab'],
                        ['1 kg', '50 mg', 'Lab'],
                        ['2 kg', '100 mg', 'Lab'],
                        ['5 kg', '250 mg', 'Lab/MY'],
                        ['10 kg', '500 mg', 'Lab/MY'],
                        ['20 kg', '1000 mg', 'Lab/MY'],
                        ['50 kg', '2500 mg', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'kutle-7',
                    'title' => 'M3 Sınıf Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1 g', '3.0 mg', 'Lab'],
                        ['2 g', '4.0 mg', 'Lab'],
                        ['5 g', '5.0 mg', 'Lab'],
                        ['10 g', '6.0 mg', 'Lab'],
                        ['20 g', '8.0 mg', 'Lab'],
                        ['50 g', '10 mg', 'Lab'],
                        ['100 g', '16 mg', 'Lab'],
                        ['200 g', '30 mg', 'Lab'],
                        ['500 g', '80 mg', 'Lab'],
                        ['1 kg', '160 mg', 'Lab/MY'],
                        ['2 kg', '300 mg', 'Lab/MY'],
                        ['5 kg', '800 mg', 'Lab/MY'],
                        ['10 kg', '1600 mg', 'Lab/MY'],
                        ['20 kg', '3000 mg', 'Lab/MY'],
                        ['50 kg', '8000 mg', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'kutle-8',
                    'title' => 'Standart Olmayan Kütle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1 g-1 kg', '1.8 mg', 'Lab'],
                        ['1-5 kg', '4.0 mg', 'Lab'],
                        ['5-20 kg', '30 mg', 'Lab'],
                        ['20-51 kg', '100 mg', 'Lab'],
                    ],
                ],
            ],
        ],

        /* ============================ 5. SERTLİK ============================ */
        [
            'slug' => 'sertlik',
            'icon' => '💠',
            'title' => 'Sertlik',
            'summary' => 'Brinell, Rockwell, Vickers, Shore ve portatif sertlik',
            'groups' => [
                [
                    'id' => 'sertlik-1',
                    'title' => 'Brinell Sertlik',
                    'columns' => ['Tip', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['HBW 10/3000', '100-450 HB', '%0.6', 'TS EN ISO 6506-2, ASTM E10', 'MY'],
                        ['HBW 5/750', '100-450 HB', '%0.9', 'TS EN ISO 6506-2, ASTM E10', 'MY'],
                        ['HBW 2.5/187.5', '100-450 HB', '%1.2', 'TS EN ISO 6506-2, ASTM E10', 'MY'],
                        ['HBW 2.5/62.5', '100-450 HB', '%0.8', 'TS EN ISO 6506-2, ASTM E10', 'MY'],
                        ['Optik Öz Ölçü (L>10 mm)', '—', '1.5E-3·L mm', 'TS EN ISO 6506-2, stage mik.', 'MY'],
                    ],
                ],
                [
                    'id' => 'sertlik-2',
                    'title' => 'Rockwell Sertlik',
                    'columns' => ['Tip', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['HRB', '1.0 HRB', 'TS EN ISO 6508-2, ASTM E18', 'MY'],
                        ['HRC', '0.5 HRC', 'TS EN ISO 6508-2, ASTM E18', 'MY'],
                    ],
                ],
                [
                    'id' => 'sertlik-3',
                    'title' => 'Vickers Sertlik',
                    'columns' => ['Tip', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['HV0.1', '%5.4', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV0.3', '%3.1', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV0.5', '%2.7', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV1', '%2.4', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV2', '%1.4', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV5', '%1.0', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                        ['HV10', '%1.0', 'TS EN ISO 6507-2, ASTM E384/E92', 'MY'],
                    ],
                ],
                [
                    'id' => 'sertlik-4',
                    'title' => 'Portatif Sertlik',
                    'columns' => ['Tip', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Rockwell (Leeb)', '30-64 HRC', '1.8 HRC', 'ISO 16859-2, sertlik plakası', 'Lab/MY'],
                        ['Leeb', '550-850 HLD', '18 HLD', 'ISO 16859-2, sertlik plakası', 'Lab/MY'],
                        ['UCI HV1', '—', '%2.4', 'ASTM A1038, sertlik plakası', 'Lab/MY'],
                        ['UCI HV2', '—', '%1.4', 'ASTM A1038, sertlik plakası', 'Lab/MY'],
                        ['UCI HV5', '—', '%1.0', 'ASTM A1038, sertlik plakası', 'Lab/MY'],
                        ['UCI HV10', '—', '%1.0', 'ASTM A1038, sertlik plakası', 'Lab/MY'],
                        ['UCI HRC', '—', '0.5 HRC', 'ASTM A1038, sertlik plakası', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'sertlik-5',
                    'title' => 'Shore Sertlik',
                    'columns' => ['Tip', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Shore A/D (kontrol plakası)', '0.6 Shore', 'ISO 48-4, ISO 48-9, ISO 868', 'Lab/MY'],
                        ['Shore (tüm tipler: A,D,AO,AM,B,C,DO,E,M,O,OO,OOO,OOO-S)', '0.5 Shore', 'ISO 48-4, ISO 48-9, ISO 868, ASTM D2240', 'Lab'],
                    ],
                ],
                [
                    'id' => 'sertlik-6',
                    'title' => 'IRHD Sertlik',
                    'columns' => ['Metot', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['N, H, L', '0.5 IRHD', 'ISO 48-2, ISO 48-9', 'MY'],
                        ['M', '0.5 IRHD', 'ISO 48-2, ISO 48-9', 'MY'],
                    ],
                ],
                [
                    'id' => 'sertlik-7',
                    'title' => 'Sertlik Uçları',
                    'columns' => ['Tip', 'Parametre', 'U', 'Yer'],
                    'rows' => [
                        ['Rockwell Küresel-Konik (A,C,D,N)', 'Açı / yarı-çap / eksenellik / doğrusallık', '0.05° / 5.0 µm / 0.05° / 1.0 µm', 'Lab'],
                        ['Vickers Piramit', 'Piramit açısı / eksen', '0.05°', 'Lab'],
                        ['Brinell / Rockwell Bilye (R=1-12.7 mm)', 'Küre çap', '(0.4+4.6L) µm', 'Lab'],
                    ],
                ],
            ],
        ],

        /* ============================ 6. HACİM ============================ */
        [
            'slug' => 'hacim',
            'icon' => '🧪',
            'title' => 'Hacim',
            'summary' => 'Pipet, büret, balon joje, mezür, dispenser ve piknometre',
            'groups' => [
                [
                    'id' => 'hacim-1',
                    'title' => 'Pipet (Pistonlu) - Tek Kanallı',
                    'columns' => ['Aralık', 'U', 'Tip', 'Yer'],
                    'rows' => [
                        ['1-3 µL', '%0.80', 'Tip A/D1', 'Lab'],
                        ['3-5 µL', '%0.60', 'Tip A/D1', 'Lab'],
                        ['5-10 µL', '%0.35', 'Tip A/D1', 'Lab'],
                        ['10-50 µL', '%0.30', 'Tip A/D1', 'Lab'],
                        ['50 µL-5 mL', '%0.20', 'Tip A/D1', 'Lab'],
                        ['5-20 mL', '%0.15', 'Tip A/D1', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-2',
                    'title' => 'Pipet (Pistonlu) - Çok Kanallı',
                    'columns' => ['Aralık', 'U', 'Tip', 'Yer'],
                    'rows' => [
                        ['2 µL', '%2.6', 'Çok kanallı', 'Lab'],
                        ['2-5 µL', '%1.0', 'Çok kanallı', 'Lab'],
                        ['5-10 µL', '%0.60', 'Çok kanallı', 'Lab'],
                        ['10-50 µL', '%0.40', 'Çok kanallı', 'Lab'],
                        ['50 µL-2 mL', '%0.32', 'Çok kanallı', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-3',
                    'title' => 'Pipet (Pistonlu) - Tip D2',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['5 µL', '%0.60', 'Lab'],
                        ['5-20 µL', '%0.40', 'Lab'],
                        ['20-100 µL', '%0.30', 'Lab'],
                        ['100 µL-1 mL', '%0.25', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-4',
                    'title' => 'Şırınga',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1-10 µL', '%1.5', 'Lab'],
                        ['10 µL-2 mL', '%1.4', 'Lab'],
                        ['2-200 mL', '%1.2', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-5',
                    'title' => 'Büret (Pistonlu) - Elle',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['<1 mL', '%0.17', 'Lab'],
                        ['1-2 mL', '%0.11', 'Lab'],
                        ['2-10 mL', '%0.08', 'Lab'],
                        ['10-100 mL', '%0.06', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-6',
                    'title' => 'Büret (Pistonlu) - Motorlu',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['<1 mL', '%0.17', 'Lab'],
                        ['1-2 mL', '%0.12', 'Lab'],
                        ['2-5 mL', '%0.08', 'Lab'],
                        ['5-25 mL', '%0.06', 'Lab'],
                        ['25-100 mL', '%0.05', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-7',
                    'title' => 'Dispenser - Tek Hareketli',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['10 µL', '%0.55', 'Lab'],
                        ['10-20 µL', '%0.45', 'Lab'],
                        ['20-50 µL', '%0.35', 'Lab'],
                        ['50-100 µL', '%0.31', 'Lab'],
                        ['100-200 µL', '%0.22', 'Lab'],
                        ['200-500 µL', '%0.20', 'Lab'],
                        ['500 µL-200 mL', '%0.14', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-8',
                    'title' => 'Dispenser - Çok Aktarımlı',
                    'columns' => ['Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['1-2 µL', '%1.3', 'Lab'],
                        ['2-3 µL', '%0.80', 'Lab'],
                        ['3-10 µL', '%0.60', 'Lab'],
                        ['10-20 µL', '%0.50', 'Lab'],
                        ['20-50 µL', '%0.30', 'Lab'],
                        ['50-200 µL', '%0.25', 'Lab'],
                        ['200-500 µL', '%0.23', 'Lab'],
                        ['500 µL-1 mL', '%0.20', 'Lab'],
                        ['1-2 mL', '%0.16', 'Lab'],
                        ['2-25 mL', '%0.12', 'Lab'],
                        ['25-200 mL', '%0.10', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-9',
                    'title' => 'Balon Joje (Cam)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['1-10 mL', '8.0 µL', 'Lab'],
                        ['20 mL', '12 µL', 'Lab'],
                        ['25 mL', '12 µL', 'Lab'],
                        ['50 mL', '18 µL', 'Lab'],
                        ['100 mL', '28 µL', 'Lab'],
                        ['200 mL', '40 µL', 'Lab'],
                        ['250 mL', '40 µL', 'Lab'],
                        ['500 mL', '70 µL', 'Lab'],
                        ['1000 mL', '0.10 mL', 'Lab'],
                        ['2000 mL', '0.16 mL', 'Lab'],
                        ['5000 mL', '0.34 mL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-10',
                    'title' => 'Balon Joje (Plastik)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['10 mL', '12 µL', 'Lab'],
                        ['25 mL', '12 µL', 'Lab'],
                        ['50 mL', '18 µL', 'Lab'],
                        ['100 mL', '26 µL', 'Lab'],
                        ['250 mL', '42 µL', 'Lab'],
                        ['500 mL', '70 µL', 'Lab'],
                        ['1000 mL', '0.12 mL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-11',
                    'title' => 'Mezür (Cam)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['5 mL', '16 µL', 'Lab'],
                        ['10 mL', '30 µL', 'Lab'],
                        ['25 mL', '62 µL', 'Lab'],
                        ['50 mL', '0.12 mL', 'Lab'],
                        ['100 mL', '0.14 mL', 'Lab'],
                        ['250 mL', '0.26 mL', 'Lab'],
                        ['500 mL', '0.60 mL', 'Lab'],
                        ['1000 mL', '1.2 mL', 'Lab'],
                        ['2000 mL', '2.4 mL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-12',
                    'title' => 'Mezür (Plastik)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['10 mL', '32 µL', 'Lab'],
                        ['25 mL', '0.16 mL', 'Lab'],
                        ['50 mL', '0.30 mL', 'Lab'],
                        ['100 mL', '0.32 mL', 'Lab'],
                        ['250 mL', '0.64 mL', 'Lab'],
                        ['500 mL', '1.6 mL', 'Lab'],
                        ['1000 mL', '3.2 mL', 'Lab'],
                        ['2000 mL', '6.6 mL', 'Lab'],
                        ['4000 mL', '16 mL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-13',
                    'title' => 'Pipet (Taksimatlı - Cam)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['0.1-0.5 mL', '1.8 µL', 'Lab'],
                        ['1 mL', '2.2 µL', 'Lab'],
                        ['2 mL', '3.0 µL', 'Lab'],
                        ['5 mL', '9.0 µL', 'Lab'],
                        ['10 mL', '15 µL', 'Lab'],
                        ['20 mL', '30 µL', 'Lab'],
                        ['25 mL', '30 µL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-14',
                    'title' => 'Pipet (Tek Ölçülü - Cam)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['0.5 mL', '1.4 µL', 'Lab'],
                        ['1 mL', '2.4 µL', 'Lab'],
                        ['2 mL', '3.2 µL', 'Lab'],
                        ['5 mL', '4.2 µL', 'Lab'],
                        ['10 mL', '6.0 µL', 'Lab'],
                        ['25 mL', '8.0 µL', 'Lab'],
                        ['50 mL', '12 µL', 'Lab'],
                        ['100 mL', '20 µL', 'Lab'],
                        ['200 mL', '30 µL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-15',
                    'title' => 'Büret (Cam - Boşaltım)',
                    'columns' => ['Hacim', 'U', 'Yer'],
                    'rows' => [
                        ['1 mL', '1.8 µL', 'Lab'],
                        ['2 mL', '3.2 µL', 'Lab'],
                        ['5 mL', '3.2 µL', 'Lab'],
                        ['10 mL', '6.0 µL', 'Lab'],
                        ['25 mL', '10 µL', 'Lab'],
                        ['50 mL', '16 µL', 'Lab'],
                        ['100 mL', '32 µL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-16',
                    'title' => 'Piknometre',
                    'columns' => ['Tip', 'Aralık', 'U', 'Yer'],
                    'rows' => [
                        ['Gay-Lussac', '1-100 mL', '7.6 µL', 'Lab'],
                        ['Reischauer', '10-100 mL', '4.4 µL', 'Lab'],
                        ['Hubbard', '25-50 mL', '32 µL', 'Lab'],
                        ['Termometreli', '10-100 mL', '10 µL', 'Lab'],
                    ],
                ],
                [
                    'id' => 'hacim-17',
                    'title' => 'Standart Kapasite Ölçüm Kapları',
                    'columns' => ['Hacim', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['1 L', '0.35 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                        ['2 L', '0.62 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                        ['5 L', '1.03 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                        ['10 L', '1.3 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                        ['20 L', '2.3 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                        ['50 L', '5.1 mL', 'EURAMET cg.21, hacimsel', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ============================ 7. TORK ============================ */
        [
            'slug' => 'tork',
            'icon' => '🔧',
            'title' => 'Tork',
            'summary' => 'Tork dönüştürücü, tork el aletleri ve sıkıcılar',
            'groups' => [
                [
                    'id' => 'tork-1',
                    'title' => 'Tork',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Tork Dönüştürücü', '1-1000 Nm', '%0.2', 'EURAMET cg.14, referans kol + ağırlık', 'Lab/MY'],
                        ['Tork Büyüteç (0.5 sınıf)', '100-2000 Nm', '%0.8', 'Referans moment kolları', 'Lab'],
                        ['Kapak Açma-Kapama', '1-50 Nm', '%0.4', 'Referans kol + ağırlık', 'Lab'],
                        ['Tork El Aletleri (sens. ile)', '0.2-813 Nm', '%0.6', 'ISO 6789-2, 1. sınıf sens.', 'Lab'],
                        ['Tork El Aletleri (hücresi)', '100-2000 Nm', '%0.7', 'ISO 6789-2, 0.5 sınıf hücresi', 'Lab'],
                        ['Sürekli Tork Sıkıcı', '0.5-450 Nm', '%1.3', '1. sınıf sens.', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ============================ 8. YOĞUNLUK ============================ */
        [
            'slug' => 'yogunluk',
            'icon' => '💧',
            'title' => 'Yoğunluk',
            'summary' => 'Hidrometre, alkolometre ve özgül ağırlık',
            'groups' => [
                [
                    'id' => 'yogunluk-1',
                    'title' => 'Yoğunluk (Hidrometre)',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Özgül Ağırlık', '600-2000 kg/m³', '0.4 kg/m³', 'NIST SP 250-78, Cuckow', 'Lab'],
                        ['Bome Hidrometre', '0-70 Bé', '0.2 Bé', 'NIST SP 250-78, Cuckow', 'Lab'],
                        ['Alkolometre', '0-100 %', '0.025 %', 'NIST SP 250-78, Cuckow', 'Lab'],
                    ],
                ],
            ],
        ],

        /* ============================ 9. ZAMAN & FREKANS ============================ */
        [
            'slug' => 'zaman',
            'icon' => '⏱️',
            'title' => 'Zaman & Frekans',
            'summary' => 'Takometre, frekans kaynakları ve zaman aralığı',
            'groups' => [
                [
                    'id' => 'zaman-1',
                    'title' => 'Frekans - Optik Takometre',
                    'columns' => ['Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['6-99.99 rpm', '0.01 rpm', '0.013 rpm + 5.6E-5 × okunan', 'Sinyal üretici + optik led', 'Lab/MY'],
                        ['99.99-999.9 rpm', '0.1 rpm', '0.12 rpm + 6.1E-5 × okunan', 'Sinyal üretici + optik led', 'Lab/MY'],
                        ['999.9-99999 rpm', '1 rpm', '1.2 rpm + 1.2E-4 × okunan', 'Sinyal üretici + optik led', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'zaman-2',
                    'title' => 'Frekans - Temaslı Takometre',
                    'columns' => ['Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['250-999.9 rpm', '0.1 rpm', '0.3 rpm + 1.8E-4 × okunan', 'Optik takometre ile karşılaştırma', 'Lab/MY'],
                        ['999.9-1500 rpm', '1 rpm', '2.0 rpm + 1.2E-4 × okunan', 'Optik takometre ile karşılaştırma', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'zaman-3',
                    'title' => 'Frekans Kaynakları (Santrifüj)',
                    'columns' => ['Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['6-99.99 rpm', '0.01 rpm', '0.022 rpm + 2.0E-4 × okunan', 'Optik takometre direkt', 'Lab/MY'],
                        ['99.99-999.9 rpm', '0.1 rpm', '0.22 rpm + 2.0E-4 × okunan', 'Optik takometre direkt', 'Lab/MY'],
                        ['999.9-99999 rpm', '1 rpm', '1.9 rpm + 1.6E-4 × okunan', 'Optik takometre direkt', 'Lab/MY'],
                    ],
                ],
                [
                    'id' => 'zaman-4',
                    'title' => 'Zaman Aralığı',
                    'columns' => ['Aralık', 'r', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['1-7200 s', '1 ms', '0.025 s + 1.2E-5·t', 'Referans kronometre', 'Lab/MY'],
                        ['7200-86400 s', '1 ms', '0.002 s + 1.5E-5·t', 'Referans kronometre', 'Lab/MY'],
                    ],
                ],
            ],
        ],

        /* ==================== 10. MALZEME TESTİ & KUVVET ==================== */
        [
            'slug' => 'malzeme',
            'icon' => '🏗️',
            'title' => 'Malzeme Testi & Kuvvet',
            'summary' => 'Çekme/basma test makineleri, kuvvet ölçerler, darbe testi',
            'groups' => [
                [
                    'id' => 'malzeme-1',
                    'title' => 'Çekme / Basma Test Makinesi',
                    'columns' => ['Aralık', 'Tür', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.01 N-1000 N', 'Ağırlık ile çekme', '%0.10', 'TS EN ISO 7500-1, ISO 7500-1, ASTM E4', 'MY'],
                        ['100 N-100 kN', '0.5 sınıf hücresi çekme', '%0.16', 'TS EN ISO 7500-1, ISO 7500-1, ASTM E4', 'MY'],
                        ['20 kN-500 kN', 'Kafes basma/çekme', '%0.16', 'TS EN ISO 7500-1, ISO 7500-1, ASTM E4', 'MY'],
                        ['10 N-500 kN', '0.5 sınıf hücresi basma', '%0.16', 'TS EN ISO 7500-1, ISO 7500-1, ASTM E4', 'MY'],
                        ['200 kN-3 MN', '1 sınıf hücresi basma', '%0.32', 'TS EN ISO 7500-1, ISO 7500-1, ASTM E4', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-2',
                    'title' => 'Ekstansometre',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.5-1000 mm', '(0.7+1.5L) µm', 'Lazer interferometre, TS EN ISO 9513, ASTM E83', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-3',
                    'title' => 'Beton Test Presi',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['200 kN-3 MN', '%0.32', 'TS EN 12390-4', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-4',
                    'title' => 'Charpy Darbe Test Cihazı',
                    'columns' => ['Aralık', 'Parametre', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.5-750 J', 'Kuvvet / pandül / açı / zaman', '%0.16 / 0.3 mm / 0.1° / 0.03 s', 'TS EN ISO 148-2, ASTM E23', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-5',
                    'title' => 'Yaylı Darbe Test Çekici',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.1-0.3 J', '0.01 J', 'TS EN 60068-2-75, kalibratör', 'Lab'],
                        ['0.3-2.0 J', '0.015 J', 'TS EN 60068-2-75, kalibratör', 'Lab'],
                        ['0.1-0.3 J (kalibratör)', '0.007 J', 'TS EN 60068-2-75, stand', 'Lab'],
                        ['0.3-2.0 J (kalibratör)', '0.008 J', 'TS EN 60068-2-75, stand', 'Lab'],
                    ],
                ],
                [
                    'id' => 'malzeme-6',
                    'title' => 'Malzeme Test Mak. Yer Değişim / Ölçme Sistemleri',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.5-1000 mm', '(0.7+1.5L) µm', 'Lazer interferometre, ASTM E2309', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-7',
                    'title' => 'İlerleme Hızı',
                    'columns' => ['Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['0.05-500 mm/min', '%0.17', 'Lazer interferometre, ASTM E2658', 'MY'],
                    ],
                ],
                [
                    'id' => 'malzeme-8',
                    'title' => 'Kuvvet',
                    'columns' => ['Cihaz', 'Aralık', 'U', 'Yöntem', 'Yer'],
                    'rows' => [
                        ['Yük hücresi / kuvvet dönüştürücü / dinamometre', '0.01 N-1000 N', '%0.10', 'DKD R 3-3, ağırlık ile', 'Lab/MY'],
                        ['Yük hücresi / kuvvet dönüştürücü / dinamometre', '0.1-50 kN', '%0.16', 'DKD R 3-3, 0.5 sınıf hücresi', 'Lab/MY'],
                        ['Tek Kapasiteli Kuvvetölçer', '1 N-50 kN', '%0.20', 'DKD R 3-3, 0.5 sınıf hücresi', 'Lab/MY'],
                    ],
                ],
            ],
        ],

    ],
];
