<?php

return [
    'site' => [
        'name' => 'MTA Endüstri',
        'tagline' => 'Endüstriyel kalibrasyon hizmetleri ve teknik ürün çözümleri',
        'description' => 'MTA Endüstri; basınç, sıcaklık, tork, devir, kütle-terazi ve hacim kalibrasyonu alanlarında hizmet veren teknik bir kurumsal web platformu olarak yapılandırılmaktadır.',
        'phone' => '+90 (216) 390 17 78',
        'fax' => '+90 (216) 390 17 88',
        'email' => 'info@mtaend.com',
        'whatsapp' => null,
        'address' => 'Bahçelievler, Köknar Sk. No:15/B, 34890 Pendik/İstanbul',
        'working_hours' => 'Çalışma saatleri yayın öncesi netleştirilecek',
        'social_links' => [
            ['name' => 'LinkedIn', 'label' => 'in', 'url' => 'https://www.linkedin.com/company/mtaendustri/'],
            ['name' => 'Instagram', 'label' => 'ig', 'url' => 'https://www.instagram.com/mtaendustri/'],
            ['name' => 'Facebook', 'label' => 'fb', 'url' => 'https://www.facebook.com/mtaend/'],
        ],
    ],

    'services' => [
        [
            'title' => 'Basınç Kalibrasyonu',
            'slug' => 'basinc-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Basınç Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Manometre, basınç transmitterleri ve basınç ölçüm cihazları için izlenebilir basınç kalibrasyonu hizmeti.',
            'summary' => 'Manometre, basınç transmitterleri ve basınç ölçüm ekipmanları için izlenebilir kalibrasyon hizmeti.',
            'answer' => 'Basınç kalibrasyonu, basınç ölçen cihazların gösterdiği değerin güvenilir referans ekipmanlarla karşılaştırılması ve ölçüm sonucunun raporlanmasıdır.',
            'body' => 'Basınç kalibrasyonu; üretim, bakım, kalite kontrol ve proses güvenliği süreçlerinde kullanılan basınç ölçüm cihazlarının güvenilirliğini doğrulamak için uygulanır. MTA Endüstri hizmet sayfası; cihaz kapsamı, ölçüm aralığı, tolerans, belirsizlik ve raporlama bilgilerinin admin panelden yönetileceği şekilde hazırlanmıştır.',
            'scope' => ['Manometre kalibrasyonu', 'Dijital manometre kontrolü', 'Basınç transmitter doğrulaması', 'Basınç sensörü kontrolü', 'Kalibrasyon etiketi ve raporlama'],
            'devices' => ['Analog manometre', 'Dijital manometre', 'Basınç transmitter', 'Basınç sensörü', 'Vakum ölçer'],
            'applications' => ['Üretim hatları', 'Bakım ekipleri', 'Kalite laboratuvarları', 'Proses tesisleri'],
            'capacity' => [
                ['parameter' => 'Bağıl basınç', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Analog/sayısal manometre, transduser ve transmitter kapsamı'],
                ['parameter' => 'Fark basınç', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Fark basınç ölçer kapsamı'],
                ['parameter' => 'Rapor tipi', 'range' => 'Kalibrasyon raporu', 'note' => 'Format admin panelden yönetilecek'],
            ],
            'scope_groups' => [
                [
                    'title' => 'Bağıl Basınç',
                    'items' => [
                        ['name' => 'Analog Manometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Sayısal Manometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Basınç Transduseri', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Basınç Transmitteri', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Fark Basınç Ölçer', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep ve cihaz bilgisinin alınması', 'Cihaz kabul ve ön kontrol', 'Referans ekipmanla ölçüm', 'Sonuçların değerlendirilmesi', 'Raporlama ve teslim'],
            'standards' => ['ISO', 'EN', 'IEC'],
            'faq' => [
                ['question' => 'Basınç kalibrasyonu ne sıklıkla yapılmalı?', 'answer' => 'Periyot; cihaz kullanım yoğunluğu, proses riski, kalite prosedürü ve sektör gerekliliklerine göre belirlenmelidir. Yayın öncesinde firma prosedürüne uygun bilgi eklenecek.'],
                ['question' => 'Kalibrasyon raporunda hangi bilgiler bulunur?', 'answer' => 'Cihaz bilgisi, ölçüm noktaları, referans bilgileri, sonuçlar ve uygunluk değerlendirmesi gibi alanlar raporda yer alabilir.'],
            ],
            'image' => 'images/services/basinc-kalibrasyonu.webp',
            'image_alt' => 'MTA Endüstri kalibrasyon hizmeti görseli',
            'cta' => 'Basınç Kalibrasyonu İçin Teklif Al',
        ],
        [
            'title' => 'Sıcaklık Kalibrasyonu',
            'slug' => 'sicaklik-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Sıcaklık Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Termometre, sıcaklık sensörü ve proses göstergeleri için raporlanabilir sıcaklık kalibrasyonu.',
            'summary' => 'Termometre, sıcaklık sensörü ve proses göstergeleri için raporlanabilir sıcaklık kalibrasyonu.',
            'answer' => 'Sıcaklık kalibrasyonu, sıcaklık ölçüm cihazlarının referans sistemlerle karşılaştırılarak doğruluk durumunun raporlanmasıdır.',
            'body' => 'Sıcaklık kalibrasyonu; sensör, termometre, sıcaklık göstergesi ve proses ekipmanlarının ölçüm güvenilirliğini değerlendirmek için kullanılır.',
            'scope' => ['Direnç ve ısıl çift sensörleri', 'Pirometre ve IR termometre', 'Kontrollü hacim sıcaklık dağılımı', 'Termometre ve higrometre kalibrasyonu', 'Sıcaklık göstergesi kontrolü'],
            'devices' => ['Direnç', 'Isıl çift sensörü', 'Pirometre', 'IR termometre', 'Sıcaklık göstergesi', 'Kontrollü hacimler'],
            'applications' => ['Laboratuvar', 'Üretim', 'Kalite kontrol'],
            'capacity' => [
                ['parameter' => 'Sensör ve gösterge', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Cihaz tipine göre alt/üst sınır değişir'],
                ['parameter' => 'Kontrollü hacimler', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Otoklav, sıvı banyo, kül fırını, etüv ve kabinler'],
                ['parameter' => 'Bağıl nem', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Higrometre ve bağıl nem ölçerler'],
            ],
            'scope_groups' => [
                [
                    'title' => 'Sensörler ve Göstergeler',
                    'items' => [
                        ['name' => 'Direnç', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Isıl çift sensörü', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Pirometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'IR Termometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Sıcaklık Göstergesi', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Soğuk Eklem ON', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Isıl Çiftler',
                    'items' => [
                        ['name' => 'Endüstriyel Isıl Çiftler T', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Platin Bazlı Referans Isıl Çiftler R', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Platin Bazlı Referans Isıl Çiftler S', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Endüstriyel Isıl Çiftler E', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Endüstriyel Isıl Çiftler K', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Endüstriyel Isıl Çiftler N', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Endüstriyel Isıl Çiftler J', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Kontrollü Hacimler',
                    'items' => [
                        ['name' => 'Sterilizatör (Otoklav)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Sıvı Banyo', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Kül Fırını', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Etüv', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'İnkübatör', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Soğuk Oda', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'İklimlendirme Kabini', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Termometreler',
                    'items' => [
                        ['name' => 'Sıvılı Cam Termometreler', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Yüzey Sıcaklık Termometreleri', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Oda Termometresi', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Duvar Tipi Termometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Masa Termometresi', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Datalogger', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Dijital Termometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Analog Termometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Buzdolabı Termometreleri', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Analog ve Sayısal Sıcaklık Ölçerler', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Nem ve PRT',
                    'items' => [
                        ['name' => 'Higrometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Bağıl Nem Ölçer (Datalogger)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Bağıl Nem Ölçer (Dijital/Analog)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Platin Direnç Termometreler (PRT)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Endüstriyel Platin Direnç Termometreler (PRT)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Termistör', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep', 'Cihaz kabul', 'Ölçüm', 'Değerlendirme', 'Rapor'],
            'standards' => ['ISO', 'EN'],
            'faq' => [],
            'image' => 'images/services/sicaklik-kalibrasyonu.jpg',
            'image_alt' => 'MTA Endüstri sıcaklık kalibrasyonu hizmet görseli',
            'cta' => 'Sıcaklık Kalibrasyonu İçin Teklif Al',
        ],
        [
            'title' => 'Tork Kalibrasyonu',
            'slug' => 'tork-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Tork Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Tork anahtarı ve tork ölçüm ekipmanları için kontrollü kalibrasyon hizmeti.',
            'summary' => 'Tork anahtarı ve tork ölçüm ekipmanları için kontrollü kalibrasyon hizmeti.',
            'answer' => 'Tork kalibrasyonu, tork uygulayan veya ölçen ekipmanların belirli noktalarda referans sistemlerle doğrulanmasıdır.',
            'body' => 'Tork kalibrasyonu; üretim, bakım ve kalite kontrol süreçlerinde kullanılan tork ekipmanlarının güvenilir ölçüm üretmesini destekler.',
            'scope' => ['Tork anahtarı kalibrasyonu', 'Tork ölçer kontrolü', 'Sıkma ekipmanı doğrulaması', 'Kalibrasyon raporu'],
            'devices' => ['Referans tork anahtarı', 'Tork el aletleri', 'Tork büyütücü'],
            'applications' => ['Montaj hatları', 'Bakım süreçleri', 'Kalite kontrol'],
            'capacity' => [['parameter' => 'Tork ölçüm aralığı', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Referans tork anahtarı, tork el aletleri ve tork büyütücü kapsamı']],
            'scope_groups' => [
                [
                    'title' => 'Tork Ölçüm Cihazları',
                    'items' => [
                        ['name' => 'Referans Tork Anahtarı', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Tork El Aletleri', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Tork Büyütücü', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep', 'Cihaz kabul', 'Ölçüm', 'Değerlendirme', 'Rapor'],
            'standards' => ['ISO', 'DIN'],
            'faq' => [],
            'image' => 'images/services/tork-kalibrasyonu.png',
            'image_alt' => 'MTA Endüstri tork kalibrasyonu hizmet görseli',
            'cta' => 'Tork Kalibrasyonu İçin Teklif Al',
        ],
        [
            'title' => 'Devir Kalibrasyonu',
            'slug' => 'devir-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Devir Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Devir, hız ve dönme ölçümü yapan cihazlar için izlenebilir kalibrasyon hizmeti.',
            'summary' => 'Devir, hız ve dönme ölçümü yapan cihazlar için izlenebilir kalibrasyon süreci.',
            'answer' => 'Devir kalibrasyonu, takometre ve benzeri cihazların dönüş hızı ölçümlerinin referans değerlerle karşılaştırılmasıdır.',
            'body' => 'Devir kalibrasyonu; takometre ve benzeri devir ölçüm cihazlarının ölçüm doğruluğunu değerlendirmek için kullanılır.',
            'scope' => ['Frekans kaynakları', 'Frekans standardı', 'Santrifüj ve karıştırıcı cihazlar', 'Raporlama'],
            'devices' => ['Frekans kaynağı', 'Frekans standardı', 'Santrifüj', 'Karıştırıcı cihazlar'],
            'applications' => ['Motor testleri', 'Bakım ekipleri', 'Üretim hatları', 'Laboratuvar cihazları'],
            'capacity' => [['parameter' => 'Frekans / devir aralığı', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Frekans kaynakları, standartları ve üreteçleri kapsamı']],
            'scope_groups' => [
                [
                    'title' => 'Frekans',
                    'items' => [
                        ['name' => 'Frekans Kaynakları', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Frekans Standardı', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Frekans Üreteci (Santrifüj-Karıştırıcı Cihazlar)', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep', 'Cihaz kabul', 'Ölçüm', 'Değerlendirme', 'Rapor'],
            'standards' => ['ISO', 'IEC'],
            'faq' => [],
            'image' => 'images/services/devir-kalibrasyonu.webp',
            'image_alt' => 'MTA Endüstri devir ve frekans kalibrasyonu hizmet görseli',
            'cta' => 'Devir Kalibrasyonu İçin Teklif Al',
        ],
        [
            'title' => 'Kütle & Terazi Kalibrasyonu',
            'slug' => 'kutle-terazi-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Kütle ve Terazi Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Terazi, kütle ve tartım ekipmanları için ölçüm güvenilirliğini destekleyen kalibrasyon hizmeti.',
            'summary' => 'Terazi, kütle ve tartım ekipmanları için ölçüm güvenilirliğini destekleyen kalibrasyon hizmeti.',
            'answer' => 'Kütle ve terazi kalibrasyonu, tartım ekipmanlarının referans kütlelerle karşılaştırılarak doğruluk durumunun belirlenmesidir.',
            'body' => 'Kütle ve terazi kalibrasyonu; tartım ekipmanlarının doğruluğunu izlenebilir referanslarla değerlendirmek için kullanılır.',
            'scope' => ['Kütle standardı kalibrasyonu', 'Tartım cihazları kalibrasyonu', 'Otomatik ağırlık kontrol terazisi', 'Etiketleme ve raporlama'],
            'devices' => ['M1 sınıfı kütle', 'M2 sınıfı kütle', 'M3 sınıfı kütle', 'Standart olmayan kütle', 'Terazi', 'Otomatik ağırlık kontrol terazisi'],
            'applications' => ['Laboratuvar', 'Depo ve sevkiyat', 'Kalite kontrol'],
            'capacity' => [
                ['parameter' => 'Kütle standardı', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Sınıf ve kütle tipine göre değişir'],
                ['parameter' => 'Tartım cihazları', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Terazi kapasitesine göre kapsamlandırılır'],
                ['parameter' => 'Otomatik ağırlık kontrol terazisi', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Cihaz tipine göre değerlendirilir'],
            ],
            'scope_groups' => [
                [
                    'title' => 'Kütle Standardı',
                    'items' => [
                        ['name' => 'M1 Sınıfı Kütle', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'M2 Sınıfı Kütle', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'M3 Sınıfı Kütle', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Standart Olmayan Kütle', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Tartım Cihazları',
                    'items' => [
                        ['name' => 'Terazi', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Otomatik Ağırlık Kontrol Terazisi', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep', 'Cihaz kabul', 'Ölçüm', 'Değerlendirme', 'Rapor'],
            'standards' => ['ISO', 'OIML'],
            'faq' => [],
            'image' => 'images/services/kutle-terazi-kalibrasyonu.webp',
            'image_alt' => 'MTA Endüstri kütle ve terazi kalibrasyonu hizmet görseli',
            'cta' => 'Kütle ve Terazi Kalibrasyonu İçin Teklif Al',
        ],
        [
            'title' => 'Hacim Kalibrasyonu',
            'slug' => 'hacim-kalibrasyonu',
            'category' => 'Kalibrasyon Hizmetleri',
            'seo_title' => 'Hacim Kalibrasyonu | MTA Endüstri',
            'meta_description' => 'Hacim ölçüm ekipmanları ve laboratuvar cam malzemeleri için kalibrasyon hizmeti.',
            'summary' => 'Hacim ölçüm ekipmanları ve laboratuvar cam malzemeleri için kalibrasyon hizmeti.',
            'answer' => 'Hacim kalibrasyonu, hacim ölçen ekipmanların belirli hacim noktalarında referans değerlerle doğrulanmasıdır.',
            'body' => 'Hacim kalibrasyonu; hacim ölçüm ekipmanlarının doğru ve tekrarlanabilir sonuç üretmesini destekler.',
            'scope' => ['Cam ve plastik hacim ekipmanları', 'Pipet, büret ve balon joje kalibrasyonu', 'Pistonlu hacim cihazları', 'Dispenser ve piknometre kapsamı', 'Raporlama'],
            'devices' => ['Cam mezür', 'Pipet', 'Büret', 'Balon joje', 'Piknometre', 'Dispenser'],
            'applications' => ['Laboratuvar', 'Üretim', 'Kalite kontrol'],
            'capacity' => [
                ['parameter' => 'Cam hacim ekipmanları', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Ekipman tipine göre değişir'],
                ['parameter' => 'Pistonlu hacim cihazları', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Pipet, büret ve dispenser kapsamı'],
                ['parameter' => 'Plastik mezür', 'range' => 'Belgeyle doğrulanacak', 'note' => 'Kapasiteye göre değerlendirilir'],
            ],
            'scope_groups' => [
                [
                    'title' => 'Hacim Ölçüm Ekipmanları',
                    'items' => [
                        ['name' => 'Cam Mezür', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Pipet (Tek Ölçülü)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Pipet (Taksimatlı)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Büret', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Balon Joje (Dar boyunlu)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Balon Joje (Geniş boyunlu)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Piknometre', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Plastik Mezür', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
                [
                    'title' => 'Pistonlu Hacim Cihazları',
                    'items' => [
                        ['name' => 'Pipet (Pistonlu)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Büret (Pistonlu)', 'range' => 'Belgeyle doğrulanacak'],
                        ['name' => 'Dispenser', 'range' => 'Belgeyle doğrulanacak'],
                    ],
                ],
            ],
            'process' => ['Talep', 'Cihaz kabul', 'Ölçüm', 'Değerlendirme', 'Rapor'],
            'standards' => ['ISO', 'EN'],
            'faq' => [],
            'image' => 'images/services/hacim-kalibrasyonu.webp',
            'image_alt' => 'MTA Endüstri hacim kalibrasyonu hizmet görseli',
            'cta' => 'Hacim Kalibrasyonu İçin Teklif Al',
        ],
    ],

    'technical_services' => [
        [
            'title' => 'Analiz ve Ölçüm Cihazları Teknik Servis',
            'slug' => 'analiz-ve-olcum-cihazlari-teknik-servis',
            'category' => 'Teknik Servis',
            'seo_title' => 'Analiz ve Ölçüm Cihazları Teknik Servis | MTA Endüstri',
            'meta_description' => 'Spektrofotometre, pH metre, iletkenlik ölçer, titrasyon cihazı ve sıcaklık test cihazları için bakım, onarım ve teknik servis hizmeti.',
            'summary' => 'Analiz ve ölçüm cihazları için arıza tespiti, bakım, parça değişimi, ölçüm stabilitesi kontrolü ve kalibrasyon öncesi hazırlık.',
            'answer' => 'Analiz ve ölçüm cihazları teknik servisi; hassas ölçüm cihazlarının arıza, bakım, sensör, prob, yazılım ve ölçüm stabilitesi ihtiyaçlarını kontrollü bir süreçle ele alır.',
            'body' => 'Yüksek hassasiyetle çalışan analiz ve ölçüm cihazlarında ölçüm güvenilirliği yalnızca kalibrasyonla değil, cihazın elektronik, sensör, prob ve yazılım sağlığıyla birlikte değerlendirilir. MTA Endüstri, cihaz kabulünden test ve teslim sürecine kadar kayıtlı ve takip edilebilir teknik servis akışı sunar.',
            'devices' => ['Spektrofotometre', 'pH metre ve iyon metre', 'İletkenlik ölçer', 'Nem ölçer', 'Titrasyon cihazları', 'Datalogger ve sıcaklık test cihazları'],
            'service_steps' => [
                ['title' => 'Elektronik kart ve sensör arıza tespiti', 'text' => 'Sensör, bağlantı, işlemci, ekran modülü ve elektronik kart kaynaklı arızalar ön testlerle belirlenir.'],
                ['title' => 'Elektrot ve prob testi / değişimi', 'text' => 'pH metre, iletkenlik ölçer ve iyon metre gibi cihazlarda elektrot ve prob performansı kontrol edilir.'],
                ['title' => 'Yazılım ve donanım güncellemesi', 'text' => 'Marka ve modele uygun firmware, donanım ve ayar kontrolleri servis sürecine dahil edilebilir.'],
                ['title' => 'Ölçüm stabilitesi ve hata kontrolü', 'text' => 'Cihazın aynı örnek üzerinde tutarlı sonuç üretip üretmediği test solüsyonlarıyla değerlendirilir.'],
                ['title' => 'Yedek parça tespiti ve montajı', 'text' => 'Arızalı komponentler için orijinal veya eşdeğer parça ihtiyacı belirlenir, montaj sonrası cihaz yeniden kontrol edilir.'],
            ],
            'advantages' => ['Tecrübeli mühendis ve teknisyen kadrosu', 'Orijinal veya uyumlu yedek parça temini', 'Kayıtlı test ve servis süreci', 'Kalibrasyon hizmetleriyle entegre ilerleme'],
            'faq' => [
                ['question' => 'Analiz cihazı servisten sonra kalibrasyona hazırlanabilir mi?', 'answer' => 'Evet. Servis sonrası cihazın ölçüm stabilitesi kontrol edilerek kalibrasyon sürecine uygunluğu değerlendirilebilir.'],
                ['question' => 'Prob veya sensör arızası teknik serviste tespit edilir mi?', 'answer' => 'Evet. Elektrot, prob, sensör ve bağlantı kaynaklı arızalar cihaz tipine göre test edilir.'],
            ],
            'image' => 'images/technical-service/analiz-olcum-cihazlari-teknik-servis.webp',
            'image_alt' => 'Analiz ve ölçüm cihazları teknik servis görseli',
            'cta' => 'Analiz Cihazı Servisi İçin Teklif Al',
        ],
        [
            'title' => 'Laboratuvar Cihazları İçin Teknik Servis',
            'slug' => 'laboratuvar-cihazlari-icin-teknik-servis',
            'category' => 'Teknik Servis',
            'seo_title' => 'Laboratuvar Cihazları İçin Teknik Servis | MTA Endüstri',
            'meta_description' => 'Laboratuvar cihazları için arıza tespiti, periyodik bakım, parça değişimi, cihaz ayarı ve kalibrasyon öncesi teknik hazırlık hizmeti.',
            'summary' => 'Laboratuvar cihazları için bakım, onarım, periyodik kontrol, yedek parça ve kalibrasyon öncesi hazırlık hizmetleri.',
            'answer' => 'Laboratuvar cihazları teknik servisi; cihazların arıza öncesi bakımını, arıza durumunda onarımını ve gerektiğinde kalibrasyon öncesi hazırlığını kapsar.',
            'body' => 'Laboratuvar cihazlarının doğru çalışması kalite kontrol ve AR-GE süreçlerinin sürekliliği için kritiktir. MTA Endüstri; sıcaklık, hacim, tartım ve analiz cihazlarında arıza tespiti, periyodik bakım, ayar, parça değişimi ve yerinde/laboratuvar ortamında servis desteği sağlar.',
            'devices' => ['Etüv', 'Fırın', 'Su banyosu', 'Termoblok', 'Pipet', 'Dağıtıcı', 'Otomatik ölçüm cihazları', 'Teraziler', 'Spektrofotometre', 'pH metre', 'İyon metre', 'Melting point cihazı'],
            'service_steps' => [
                ['title' => 'Arıza tespiti ve onarım', 'text' => 'Cihazın fiziksel, elektronik ve fonksiyonel kontrolleri yapılarak arıza kaynağı belirlenir.'],
                ['title' => 'Periyodik bakım hizmeti', 'text' => 'Cihazın kullanım yoğunluğuna göre bakım, temizlik, kontrol ve performans değerlendirmesi planlanır.'],
                ['title' => 'Kalibrasyon öncesi kontrol ve hazırlık', 'text' => 'Kalibrasyon öncesinde cihazın ölçüm davranışı, stabilitesi ve temel fonksiyonları kontrol edilir.'],
                ['title' => 'Parça değişimi ve cihaz ayarı', 'text' => 'Gereken parça değişimi yapıldıktan sonra cihaz ayarları kullanım senaryosuna göre düzenlenir.'],
                ['title' => 'Yerinde veya laboratuvar ortamında servis', 'text' => 'Arıza tipine göre yerinde müdahale veya detaylı laboratuvar servis süreci yürütülür.'],
            ],
            'advantages' => ['Laboratuvar cihazlarında kapsamlı servis tecrübesi', 'Sertifikalı teknik ekip yaklaşımı', 'Yerinde veya laboratuvar ortamında müdahale', 'Orijinal yedek parça ve kayıtlı servis süreci'],
            'faq' => [
                ['question' => 'Cihazımı yerinde onarabilir misiniz?', 'answer' => 'Arızanın türüne göre yerinde servis verilebilir. Gerekli durumlarda cihaz detaylı test için servise alınır.'],
                ['question' => 'Bakım sonrası kalibrasyon yapılabilir mi?', 'answer' => 'Evet. Talebe göre bakım ve teknik kontrol sonrası ilgili kalibrasyon hizmeti de planlanabilir.'],
                ['question' => 'Yedek parça değişimi kayıt altına alınır mı?', 'answer' => 'Evet. Değişen parça, yapılan işlem ve servis sonucu kayıtlı şekilde takip edilebilir.'],
            ],
            'image' => 'images/technical-service/laboratuvar-cihazlari-teknik-servis.webp',
            'image_alt' => 'Laboratuvar cihazları teknik servis görseli',
            'cta' => 'Laboratuvar Cihazı Servisi İçin Teklif Al',
        ],
        [
            'title' => 'Terazi Teknik Servis',
            'slug' => 'terazi-teknik-servis',
            'category' => 'Teknik Servis',
            'seo_title' => 'Terazi Teknik Servis | MTA Endüstri',
            'meta_description' => 'Analitik, hassas, platform, zemin, vinç ve dolum terazileri için arıza tespiti, bakım, loadcell kontrolü ve kalibrasyon öncesi hazırlık.',
            'summary' => 'Hassas, analitik ve endüstriyel teraziler için arıza tespiti, bakım, onarım, loadcell kontrolü ve kalibrasyon öncesi hazırlık.',
            'answer' => 'Terazi teknik servisi; tartım cihazlarında mekanik, elektronik, loadcell, ekran, tuş takımı ve tartım sapması kaynaklı sorunların tespit edilip giderilmesini kapsar.',
            'body' => 'Hassas ve endüstriyel teraziler zaman içinde mekanik, elektronik veya kullanım kaynaklı ölçüm sorunları yaşayabilir. MTA Endüstri; terazi arızalarının tespiti, tartım sapması analizi, yük hücresi kontrolü, elektronik kart değişimi ve kalibrasyon öncesi teknik hazırlık süreçlerini birlikte ele alır.',
            'devices' => ['Mikro ve analitik teraziler', 'Masaüstü hassas teraziler', 'Platform ve zemin terazileri', 'Vinç ve dolum terazileri', 'Ticari kullanıma uygun teraziler'],
            'service_steps' => [
                ['title' => 'Mekanik ve elektronik arıza tespiti', 'text' => 'Ağırlık algılamama, hatalı tartım, ekran donması ve tuş arızaları cihaz üzerinde test edilir.'],
                ['title' => 'Tartım sapması analizi ve düzeltme', 'text' => 'Referans testlerle cihazın tartım davranışı incelenir, sapma kaynakları belirlenir.'],
                ['title' => 'Yük hücresi kontrol ve değişimi', 'text' => 'Loadcell performansı kontrol edilir; gerekirse değişim sonrası cihaz yeniden ayarlanır.'],
                ['title' => 'Elektronik kart ve ekran modülü değişimi', 'text' => 'Ekran, kontrol paneli, anakart ve bağlantı kaynaklı sorunlar servis sürecinde değerlendirilir.'],
                ['title' => 'Kalibrasyon öncesi teknik hazırlık', 'text' => 'Temizlik, sabitleme, sensör kontrolü ve temel performans testleriyle cihaz kalibrasyona hazırlanır.'],
            ],
            'advantages' => ['Çok markalı terazi servis yaklaşımı', 'Yerinde servis imkanı', 'Kalibrasyonla entegre teknik kontrol', 'Hızlı müdahale ve kayıtlı servis süreci'],
            'faq' => [
                ['question' => 'Terazim sürekli farklı tartıyor, sebebi ne olabilir?', 'answer' => 'Sensör aşınması, kalibrasyon kaybı, mekanik sorunlar veya ortam etkileri buna neden olabilir. Teknik servis kontrolüyle sebep belirlenebilir.'],
                ['question' => 'Kalibrasyondan önce servis önerilir mi?', 'answer' => 'Evet. Cihazda mekanik veya elektronik sorun varsa önce teknik servis kontrolü yapılması kalibrasyon doğruluğu için daha sağlıklıdır.'],
            ],
            'image' => 'images/technical-service/terazi-teknik-servis.jpg',
            'image_alt' => 'Terazi teknik servis görseli',
            'cta' => 'Terazi Servisi İçin Teklif Al',
        ],
        [
            'title' => 'Tork Anahtarları Servisi',
            'slug' => 'tork-anahtarlari-servisi',
            'category' => 'Teknik Servis',
            'seo_title' => 'Tork Anahtarları Servisi | MTA Endüstri',
            'meta_description' => 'Tork anahtarları için arıza tespiti, bakım, kontrol, ayar ve kalibrasyon öncesi teknik servis hizmeti.',
            'summary' => 'Tork anahtarları için arıza tespiti, bakım, kontrol, ayar ve kalibrasyon öncesi teknik hazırlık hizmetleri.',
            'answer' => 'Tork anahtarları servisi; tork uygulayan el aletlerinde mekanik kontrol, ayar, bakım ve kalibrasyon öncesi teknik değerlendirme sürecini kapsar.',
            'body' => 'Tork anahtarları üretim, montaj, bakım ve kalite kontrol süreçlerinde doğru sıkma kuvvetinin uygulanması için kullanılır. MTA Endüstri; tork anahtarlarında arıza tespiti, mekanik kontrol, kilitleme ve ayar kontrolü, bakım ve kalibrasyon öncesi hazırlık desteği sunar.',
            'devices' => ['Tork anahtarları', 'Klik tip tork anahtarları', 'Dijital tork anahtarları', 'Tork el aletleri', 'Tork uygulama ekipmanları'],
            'service_steps' => [
                ['title' => 'Mekanik durum kontrolü', 'text' => 'Gövde, kilitleme mekanizması, bağlantı ucu ve genel çalışma durumu kontrol edilir.'],
                ['title' => 'Arıza tespiti ve bakım', 'text' => 'Tekrarlanabilirlik, boşluk, sıkışma veya ayar kaynaklı sorunlar servis sürecinde değerlendirilir.'],
                ['title' => 'Ayar ve fonksiyon kontrolü', 'text' => 'Cihazın kullanım amacına göre temel fonksiyonları ve ayar davranışı kontrol edilir.'],
                ['title' => 'Kalibrasyon öncesi hazırlık', 'text' => 'Servis sonrası tork anahtarının kalibrasyon sürecine uygunluğu teknik olarak değerlendirilir.'],
            ],
            'advantages' => ['Tork ekipmanlarında teknik servis deneyimi', 'Kalibrasyon süreciyle entegre ilerleme', 'Kayıtlı servis ve kontrol akışı', 'Çok markalı servis yaklaşımı'],
            'faq' => [
                ['question' => 'Tork anahtarı servisten sonra kalibrasyona alınabilir mi?', 'answer' => 'Evet. Servis sonrası cihazın uygunluğu kontrol edilerek tork kalibrasyonu süreci planlanabilir.'],
                ['question' => 'Tork anahtarı ayar problemi servis kapsamında değerlendirilir mi?', 'answer' => 'Evet. Ayar, kilitleme ve mekanik çalışma problemleri cihaz durumuna göre teknik servis kapsamında incelenebilir.'],
            ],
            'image' => 'images/services/tork-kalibrasyonu.png',
            'image_alt' => 'Tork anahtarları teknik servis görseli',
            'cta' => 'Tork Anahtarı Servisi İçin Teklif Al',
        ],
    ],

    'product_categories' => [
        ['name' => 'Teraziler', 'slug' => 'teraziler', 'summary' => 'Laboratuvar ve endüstriyel tartım süreçleri için terazi çözümleri.', 'aliases' => ['Terazi', 'Hassas Teraziler', 'Analitik Terazi']],
        ['name' => 'Analitik Teraziler', 'slug' => 'analitik-teraziler', 'parent_slug' => 'teraziler', 'summary' => 'Laboratuvar analizleri için yüksek hassasiyetli analitik teraziler.', 'aliases' => ['Analitik Terazi', 'Analitik Teraziler']],
        ['name' => 'Hassas Teraziler', 'slug' => 'hassas-teraziler', 'parent_slug' => 'teraziler', 'summary' => 'Rutin laboratuvar tartımları için hassas terazi modelleri.', 'aliases' => ['Hassas Terazi', 'Hassas Teraziler']],
        ['name' => 'Endüstriyel Teraziler', 'slug' => 'endustriyel-teraziler', 'parent_slug' => 'teraziler', 'summary' => 'Üretim ve saha tartım süreçleri için endüstriyel teraziler.', 'aliases' => ['Endüstriyel Terazi', 'Endustriyel Teraziler']],
        ['name' => 'Mikro Teraziler', 'slug' => 'mikro-teraziler', 'parent_slug' => 'teraziler', 'summary' => 'Mikro ve yarı mikro tartım ihtiyaçları için terazi çözümleri.', 'aliases' => ['Mikro Terazi', 'Mikro Teraziler']],
        ['name' => 'Nem Tayin', 'slug' => 'nem-tayin', 'summary' => 'Numune nem oranı ölçümü için nem tayin cihazları.', 'aliases' => ['Nemtayin', 'Nem Tayin Cihazları', 'Nem Tayin Cihazı']],
        ['name' => 'Titratörler', 'slug' => 'titratorler', 'summary' => 'Laboratuvar titrasyon analizleri için otomatik titratör, Karl Fischer ve büret çözümleri.', 'aliases' => ['Titratörler', 'Titratorler', 'Titrasyon Cihazları']],
        ['name' => 'Kral Fischer', 'slug' => 'kral-fischer', 'parent_slug' => 'titratorler', 'summary' => 'Su miktarı tayini için Karl Fischer titrasyon çözümleri.', 'aliases' => ['KralFischer', 'Karl Fischer', 'Kral Fischer']],
        ['name' => 'Karl Fischer Titratörler', 'slug' => 'karl-fischer-titratorler', 'parent_slug' => 'titratorler', 'summary' => 'Karl Fischer yöntemiyle su tayini için titratör ve modül çözümleri.', 'aliases' => ['Karl Fischer Titratör', 'Karl Fischer Titratorler', 'KF Titratörler', 'KF Titratorler']],
        ['name' => 'Kulometrik Karl Fischer Titratörler', 'slug' => 'kulometrik-karl-fischer-titratorler', 'parent_slug' => 'karl-fischer-titratorler', 'summary' => 'Düşük su miktarı ve iz nem analizleri için kulometrik Karl Fischer titratör sistemleri.', 'aliases' => ['Kulometrik Karl Fischer', 'Kulometrik KF Titratör', 'KF Trace']],
        ['name' => 'Volümetrik Karl Fischer Titratörler', 'slug' => 'volumetrik-karl-fischer-titratorler', 'parent_slug' => 'karl-fischer-titratorler', 'summary' => 'Numunelerdeki su miktarının volümetrik Karl Fischer yöntemiyle belirlenmesi için titratörler.', 'aliases' => ['Volümetrik Karl Fischer', 'Volumetrik Karl Fischer', 'Volümetrik KF Titratör']],
        ['name' => 'Potansiyometrik Titratörler', 'slug' => 'potansiyometrik-titratorler', 'parent_slug' => 'titratorler', 'summary' => 'Laboratuvar titrasyon analizleri için potansiyometrik titratörler.', 'aliases' => ['Potensiyometre Titratör', 'Potansiyometre Titratör', 'Potansiyomerik Titratörler', 'Potansyometrik Titratörler ve Kral Fischer']],
        ['name' => 'Piston Büretler', 'slug' => 'piston-buretler', 'parent_slug' => 'potansiyometrik-titratorler', 'summary' => 'Dozajlama, solüsyon hazırlama ve manuel titrasyon işlemleri için piston büret sistemleri.', 'aliases' => ['Piston Büret', 'Piston Buret', 'Büretler', 'Buretler', 'TITRONIC']],
        ['name' => 'Fotometrik Ölçüm Elektrodu', 'slug' => 'fotometrik-olcum-elektrodu', 'parent_slug' => 'potansiyometrik-titratorler', 'summary' => 'Fotometrik titrasyon uygulamaları için ölçüm elektrodları.', 'aliases' => ['Fotometrik Elektrod', 'Fotometrik Elektrot', 'Titrasyon Elektrodu']],
        ['name' => 'Metal Kombine Elektrodlar', 'slug' => 'metal-kombine-elektrodlar', 'parent_slug' => 'potansiyometrik-titratorler', 'summary' => 'Redoks, Karl Fischer ve metal ölçüm uygulamaları için kombine elektrodlar.', 'aliases' => ['Metal Elektrod', 'Metal Elektrot', 'Redoks Elektrodu', 'Karl Fischer Elektrodu']],
        ['name' => 'Referans Elektrodlar', 'slug' => 'referans-elektrodlar', 'parent_slug' => 'potansiyometrik-titratorler', 'summary' => 'Elektrokimyasal ölçümlerde kullanılan referans sistemli elektrodlar.', 'aliases' => ['Referans Elektrotlar', 'Referans Elektrodu', 'Reference Electrode']],
        ['name' => 'Sıcaklık Ölçüm Elektrodları', 'slug' => 'sicaklik-olcum-elektrodlari', 'parent_slug' => 'potansiyometrik-titratorler', 'summary' => 'Laboratuvar ölçüm sistemlerinde kullanılan sıcaklık ölçüm elektrodları.', 'aliases' => ['Sıcaklık Elektrodları', 'Sıcaklık Elektrotları', 'Sıcaklık Probu', 'Temperature Electrode']],
        ['name' => 'Densitometre', 'slug' => 'densitometre', 'summary' => 'Yoğunluk ve özgül ağırlık ölçümleri için densitometre çözümleri.', 'aliases' => ['Densto Metre', 'Densito Metre', 'Yoğunluk / Özgül Ağırlık Ölçer']],
        ['name' => 'Yoğunluk Ölçerler', 'slug' => 'yogunluk-olcerler', 'parent_slug' => 'densitometre', 'summary' => 'Sıvı numunelerde yoğunluk ve özgül ağırlık ölçümü için yoğunluk ölçer cihazlar.', 'aliases' => ['Yoğunluk Ölçer', 'Yogunluk Olcerler', 'Density Meter', 'DSG Yoğunluk Ölçer']],
        ['name' => 'Refraktometre', 'slug' => 'refraktometre', 'summary' => 'Kırılma indisi ve konsantrasyon ölçümü için refraktometreler.', 'aliases' => ['Retroktometre', 'Refraktometreler']],
        ['name' => 'Laboratuvar Tipi Refraktometreler', 'slug' => 'laboratuvar-tipi-refraktometreler', 'parent_slug' => 'refraktometre', 'summary' => 'Laboratuvar ve kalite kontrol uygulamaları için masa tipi dijital refraktometreler.', 'aliases' => ['Laboratuar Tipi Refraktometreler', 'Laboratuvar Refraktometresi', 'Dijital Refraktometreler', 'RFM Refraktometre']],
        ['name' => 'Taşınabilir Tip Optik Refraktometreler', 'slug' => 'tasinabilir-tip-optik-refraktometreler', 'parent_slug' => 'refraktometre', 'summary' => 'Saha ve hızlı kontrol uygulamaları için taşınabilir optik refraktometre serileri.', 'aliases' => ['Taşınabilir Optik Refraktometreler', 'El Tipi Refraktometre', 'Optik Refraktometre', 'E-Line Refraktometre', 'Eclipse Refraktometre']],
        ['name' => 'Taşınabilir Tip Dijital Refraktometreler', 'slug' => 'tasinabilir-tip-dijital-refraktometreler', 'parent_slug' => 'refraktometre', 'summary' => 'Saha, proses ve hızlı kontrol uygulamaları için taşınabilir dijital refraktometre modelleri.', 'aliases' => ['Taşınabilir Dijital Refraktometreler', 'Dijital El Tipi Refraktometre', 'OPTi Refraktometre', 'OPTi Dijital Refraktometre']],
        ['name' => 'pH Metre', 'slug' => 'ph-metre', 'summary' => 'Laboratuvar ve saha kullanımı için pH ölçüm cihazları.', 'aliases' => ['PH Metre', 'pH metre']],
        ['name' => 'Çözünmüş Oksijen Ölçüm Elektrodları', 'slug' => 'cozunmus-oksijen-olcum-elektrodlari', 'parent_slug' => 'ph-metre', 'summary' => 'Çözünmüş oksijen ölçümleri için galvanik ve optik sensörlü elektrodlar.', 'aliases' => ['Elektrodlar', 'Elektrotlar', 'Oksijen Elektrodu', 'Çözünmüş Oksijen Elektrodu', 'DO Elektrodu']],
        ['name' => 'İletkenlik Ölçüm Elektrodları', 'slug' => 'iletkenlik-olcum-elektrodlari', 'parent_slug' => 'ph-metre', 'summary' => 'Laboratuvar ve saha iletkenlik ölçümleri için elektrod ve hücreler.', 'aliases' => ['İletkenlik Elektrodu', 'İletkenlik Elektrotları', 'Conductivity Electrode']],
        ['name' => 'İyon Seçici Elektrodlar', 'slug' => 'iyon-secici-elektrodlar', 'parent_slug' => 'ph-metre', 'summary' => 'Belirli iyon parametrelerinin ölçümü için iyon seçici elektrodlar.', 'aliases' => ['ISE Elektrod', 'İyon Elektrodu', 'İyon Seçici Elektrotlar']],
        ['name' => 'Kombine pH Elektrodları', 'slug' => 'kombine-ph-elektrodlari', 'parent_slug' => 'ph-metre', 'summary' => 'BlueLine, TopLine ve Memosens serisi kombine pH elektrodları.', 'aliases' => ['pH Elektrodu', 'pH Elektrotları', 'Kombine pH Elektrotları']],
        ['name' => 'Elektrod Bağlantı Kabloları', 'slug' => 'elektrod-baglanti-kablolari', 'parent_slug' => 'ph-metre', 'summary' => 'pH, redoks, iyon seçici ve referans elektrodlar için elektrod bağlantı kabloları.', 'aliases' => ['Elektrot Bağlantı Kabloları', 'Elektrod Kablosu', 'Elektrot Kablosu', 'Bağlantı Kablosu', 'L Soket', 'BNC Kablo', 'DIN Kablo', 'Banana Kablo']],
        ['name' => 'pH İletkenlik & Metreler', 'slug' => 'ph-iletkenlik', 'summary' => 'pH metre, iletkenlik ve çok parametreli ölçüm cihazları.', 'aliases' => ['pH&İletkenlik', 'pH-İletkenlik Ölçerler', 'pH ve İletkenlik', 'pH Metre']],
        ['name' => 'Viskozimetre', 'slug' => 'viskozimetre', 'summary' => 'Akışkanların viskozite ölçümü için viskozimetre çözümleri.', 'aliases' => ['Viskozimetreler']],
        ['name' => 'Rotasyonel Viskozimetre', 'slug' => 'rotasyonel-viskozimetre', 'parent_slug' => 'viskozimetre', 'summary' => 'Sıvı ve yarı akışkan numunelerde rotasyonel ölçüm prensibiyle viskozite ölçümü yapan laboratuvar cihazları.', 'aliases' => ['Rotasyonel Viskozimetre', 'Rotasyonal Viskometre', 'Rotational Viscometer']],
        ['name' => 'Tekstür Analiz Cihazı', 'slug' => 'tekstur-analiz-cihazi', 'parent_slug' => 'viskozimetre', 'summary' => 'Gıda, kozmetik, ilaç ve malzeme laboratuvarlarında doku, sertlik, kırılma ve benzeri tekstür analizleri için kullanılan cihazlar.', 'aliases' => ['Tekstür Analiz Cihazı', 'Tekstur Analiz Cihazi', 'Texture Analyzer', 'Tekstür Analiz Cihazları']],
        ['name' => 'Karıştırıcılar', 'slug' => 'karistiricilar', 'summary' => 'Karıştırma, çalkalama, homojenizasyon ve çevre analiz cihazları.', 'aliases' => ['Karıştırıcılar', 'Karistiricilar']],
        ['name' => 'Manyetik Karıştırıcılar', 'slug' => 'manyetik-karistirici', 'parent_slug' => 'karistiricilar', 'summary' => 'Isıtmalı ve ısıtmasız manyetik karıştırıcı modelleri.', 'aliases' => ['Manyetik Karıştırıcı', 'Manyetik Karıştırıcılar']],
        ['name' => 'Isıtmalı Manyetik Karıştırıcılar', 'slug' => 'isitmali-manyetik-karistirici', 'parent_slug' => 'manyetik-karistirici', 'summary' => 'Karıştırma ile birlikte kontrollü ısıtma sağlayan manyetik karıştırıcılar.', 'aliases' => ['Isıtmalı Manyetik Karıştırıcı', 'Isitmali Manyetik Karistirici']],
        ['name' => 'Isıtmasız Manyetik Karıştırıcılar', 'slug' => 'isitmasiz-manyetik-karistirici', 'parent_slug' => 'manyetik-karistirici', 'summary' => 'Yalnızca karıştırma işlemi için kullanılan manyetik karıştırıcılar.', 'aliases' => ['Isıtmasız Manyetik Karıştırıcı', 'Isitmasiz Manyetik Karistirici']],
        ['name' => 'Mekanik Karıştırıcılar', 'slug' => 'mekanik-karistirici', 'parent_slug' => 'karistiricilar', 'summary' => 'Yüksek hacimli veya yoğun numuneler için mekanik karıştırıcılar.', 'aliases' => ['Mekanik Karıştırıcı', 'Mekanik Karıştırıcılar']],
        ['name' => 'Vorteks Karıştırıcılar', 'slug' => 'vorteks-karistiricilar', 'parent_slug' => 'karistiricilar', 'summary' => 'Tüp ve küçük hacimli numuneler için vorteks karıştırıcılar.', 'aliases' => ['Vorteks Karıştırıcı', 'Vorteks Karıştırıcılar']],
        ['name' => 'Homojenizatör', 'slug' => 'homojenizator', 'parent_slug' => 'karistiricilar', 'summary' => 'Numune hazırlama süreçleri için homojenizatör cihazları.', 'aliases' => ['Homojenizator']],
        ['name' => 'Termoreaktör', 'slug' => 'termoreaktor', 'parent_slug' => 'karistiricilar', 'summary' => 'Kimyasal analizlerde kontrollü reaksiyon ve sindirim cihazları.', 'aliases' => ['Termoreaktor']],
        ['name' => 'Jar Test', 'slug' => 'jar-test', 'parent_slug' => 'karistiricilar', 'summary' => 'Su ve atık su uygulamalarında flokülasyon/jar test cihazları.', 'aliases' => ['Jar Test', 'Flokülatör', 'Flokulator']],
        ['name' => 'Diğer Çevre Cihazları', 'slug' => 'diger-cevre-cihazlari', 'parent_slug' => 'karistiricilar', 'summary' => 'Çevre laboratuvarları için destekleyici analiz ve numune hazırlama cihazları.', 'aliases' => ['Diğer Çevre Cihazları', 'Cevre Cihazlari']],
        ['name' => 'Soğutmalı İnkübatör', 'slug' => 'sogutmali-inkubator', 'parent_slug' => 'karistiricilar', 'summary' => 'Soğutmalı inkübasyon uygulamaları için sıcaklık kontrollü cihazlar.', 'aliases' => ['Soğutmalı İnkübatör', 'Sogutmali Inkubator']],
        ['name' => 'BOİ Ölçüm Cihazı', 'slug' => 'boi-olcum-cihazi', 'parent_slug' => 'karistiricilar', 'summary' => 'BOİ ölçümü ve çevre analizleri için laboratuvar cihazları.', 'aliases' => ['BOİ Ölçüm Cihazı', 'BOD Ölçüm Cihazı', 'BOI Olcum Cihazi']],
        ['name' => 'Hot Plate', 'slug' => 'hot-plate', 'parent_slug' => 'karistiricilar', 'summary' => 'Laboratuvar ısıtma uygulamaları için hot plate cihazları.', 'aliases' => ['Hot Plate', 'Isıtıcı Tabla', 'Isitici Tabla']],
        ['name' => 'Rotatör Çalkalayıcı', 'slug' => 'rotator-calkalayici', 'parent_slug' => 'karistiricilar', 'summary' => 'Rotasyon ve çalkalama uygulamaları için laboratuvar çalkalayıcıları.', 'aliases' => ['Rotatör Çalkalayıcı', 'Rotator Calkalayici']],
        ['name' => 'Su Banyoları', 'slug' => 'su-banyolari', 'summary' => 'Laboratuvar sıcaklık kontrollü su banyosu sistemleri.', 'aliases' => ['Su Banyoları', 'Su Banyosu']],
        ['name' => 'Su Banyosu', 'slug' => 'su-banyosu', 'parent_slug' => 'su-banyolari', 'summary' => 'Sıcaklık kontrollü klasik laboratuvar su banyosu cihazları.', 'aliases' => ['Su Banyosu']],
        ['name' => 'Ultrasonik Banyo', 'slug' => 'ultrasonik-banyo', 'parent_slug' => 'su-banyolari', 'summary' => 'Temizleme ve numune hazırlama süreçleri için ultrasonik banyolar.', 'aliases' => ['Ultrasonik Banyo', 'Ultrasonik Banyolar']],
        ['name' => 'Santrifüjler', 'slug' => 'santrifujler', 'summary' => 'Numune ayırma süreçleri için laboratuvar santrifüjleri.', 'aliases' => ['Santrifüjler', 'Santrifujler', 'Santrifüj']],
        ['name' => 'İnkübatörler', 'slug' => 'inkubatorler', 'summary' => 'Sıcaklık kontrollü inkübasyon uygulamaları için cihazlar.', 'aliases' => ['İnkübatörler', 'Inkubatorler', 'İnkübatör']],
        ['name' => 'Erime Noktası', 'slug' => 'erime-noktasi', 'summary' => 'Erime noktası tayini için laboratuvar analiz cihazları.', 'aliases' => ['Erime Noktası', 'Erime Noktası Tayin']],
        ['name' => 'Polarimetreler', 'slug' => 'polarimetreler', 'summary' => 'Optik rotasyon ve konsantrasyon ölçümü için polarimetreler.', 'aliases' => ['Polarimetreler', 'Polarimetre']],
        ['name' => 'Etüv', 'slug' => 'etuv', 'summary' => 'Laboratuvar kurutma ve ısıtma süreçleri için etüv cihazları.', 'aliases' => ['Etuv']],
        ['name' => 'Balon Isıtıcılar', 'slug' => 'balon-isiticilar', 'summary' => 'Laboratuvar cam balonları için kontrollü ısıtma çözümleri.', 'aliases' => ['Balon Isıtıcı']],
    ],

    'product_brands' => [
        ['name' => 'VELP', 'slug' => 'velp', 'summary' => 'Laboratuvar cihazları ve numune hazırlama çözümleri.', 'aliases' => ['Velp Scientifica Srl'], 'logo' => 'images/brands/velp.png'],
        ['name' => 'Weightlab', 'slug' => 'weightlab', 'summary' => 'Tartım ve hassas terazi çözümleri.', 'aliases' => ['WEİGHTLAB', 'Weightlab Instruments'], 'logo' => 'images/brands/weightlab.png'],
        ['name' => 'A&D', 'slug' => 'and', 'summary' => 'Laboratuvar tartım ve hassas terazi ürünleri.', 'aliases' => ['AND', 'AnD'], 'logo' => 'images/brands/and.png'],
        ['name' => 'Cole-Parmer Stuart', 'slug' => 'stuart', 'summary' => 'Cole-Parmer Stuart; laboratuvar karıştırma, ısıtma, inkübasyon ve erime noktası tayin cihazları.', 'aliases' => ['STUART', 'Stuart', 'Cole Parmer Stuart', 'Cole-Parmer Stuart', 'COLE-PARMER STUART']],
        ['name' => 'Lamy', 'slug' => 'lamy', 'summary' => 'Reoloji ve viskozite ölçüm cihazları.', 'aliases' => ['LAMİ', 'Lamy Rheology'], 'logo' => 'images/brands/lamy.png'],
        ['name' => 'Mettler Toledo', 'slug' => 'mettler-toledo', 'summary' => 'Laboratuvar ölçüm, tartım ve analiz sistemleri.', 'aliases' => ['METTLER TOLEDO'], 'logo' => 'images/brands/mettler-toledo.png'],
        ['name' => 'Ohaus', 'slug' => 'ohaus', 'summary' => 'Terazi, nem tayin ve laboratuvar cihazları.', 'aliases' => ['OHAOUS', 'OHAUS'], 'logo' => 'images/brands/ohaus.png'],
        ['name' => 'WTW', 'slug' => 'wtw', 'summary' => 'Su analizi, pH ve iletkenlik ölçüm cihazları.', 'aliases' => ['WTW']],
        ['name' => 'Shimadzu', 'slug' => 'shimadzu', 'summary' => 'Analitik cihazlar ve laboratuvar çözümleri.', 'aliases' => ['SHIMADZU'], 'logo' => 'images/brands/shimadzu.png'],
        ['name' => 'Kyoto KEM', 'slug' => 'kyoto-kem', 'summary' => 'Titrasyon, yoğunluk ve refraktometre sistemleri.', 'aliases' => ['KYOTO KEM', 'KYOTE KEM', 'Kyoto Kem'], 'logo' => 'images/brands/kyoto-kem.png'],
        ['name' => 'Bellingham + Stanley', 'slug' => 'bellingham-stanley', 'summary' => 'Refraktometre ve polarimetre çözümleri.', 'aliases' => ['BELİNGHAMSTARLY', 'Bellingham and Stanley'], 'logo' => 'images/brands/bellingham-stanley.png'],
        ['name' => 'SI Analitik', 'slug' => 'si-analitik', 'summary' => 'Elektrokimya ve titrasyon cihazları.', 'aliases' => ['SI ANALİTİK', 'SI ANALATİK']],
    ],

    'product_category_brands' => [
        'teraziler' => ['and', 'shimadzu', 'ohaus', 'weightlab'],
        'analitik-teraziler' => ['and', 'shimadzu', 'ohaus', 'weightlab'],
        'hassas-teraziler' => ['and', 'shimadzu', 'ohaus', 'weightlab'],
        'endustriyel-teraziler' => ['and', 'weightlab'],
        'mikro-teraziler' => ['and', 'shimadzu'],
        'nem-tayin' => ['and', 'ohaus', 'weightlab', 'shimadzu'],
        'titratorler' => ['mettler-toledo', 'si-analitik', 'kyoto-kem'],
        'kral-fischer' => ['mettler-toledo', 'si-analitik', 'kyoto-kem'],
        'karl-fischer-titratorler' => ['si-analitik', 'mettler-toledo', 'kyoto-kem'],
        'kulometrik-karl-fischer-titratorler' => ['si-analitik'],
        'volumetrik-karl-fischer-titratorler' => ['si-analitik'],
        'potansiyometrik-titratorler' => ['mettler-toledo', 'si-analitik', 'kyoto-kem'],
        'piston-buretler' => ['si-analitik'],
        'fotometrik-olcum-elektrodu' => ['si-analitik'],
        'metal-kombine-elektrodlar' => ['si-analitik'],
        'referans-elektrodlar' => ['si-analitik'],
        'sicaklik-olcum-elektrodlari' => ['si-analitik'],
        'densitometre' => ['kyoto-kem', 'mettler-toledo', 'bellingham-stanley'],
        'yogunluk-olcerler' => ['bellingham-stanley'],
        'refraktometre' => ['kyoto-kem', 'mettler-toledo', 'bellingham-stanley'],
        'laboratuvar-tipi-refraktometreler' => ['bellingham-stanley'],
        'tasinabilir-tip-optik-refraktometreler' => ['bellingham-stanley'],
        'tasinabilir-tip-dijital-refraktometreler' => ['bellingham-stanley'],
        'ph-metre' => ['mettler-toledo', 'ohaus', 'wtw', 'velp'],
        'cozunmus-oksijen-olcum-elektrodlari' => ['si-analitik'],
        'iletkenlik-olcum-elektrodlari' => ['si-analitik'],
        'iyon-secici-elektrodlar' => ['si-analitik'],
        'kombine-ph-elektrodlari' => ['si-analitik'],
        'elektrod-baglanti-kablolari' => ['si-analitik'],
        'ph-iletkenlik' => ['mettler-toledo', 'ohaus', 'wtw'],
        'viskozimetre' => ['lamy'],
        'rotasyonel-viskozimetre' => ['lamy'],
        'tekstur-analiz-cihazi' => ['lamy'],
        'karistiricilar' => ['velp', 'weightlab', 'ohaus', 'stuart'],
        'isitmali-manyetik-karistirici' => ['velp', 'weightlab', 'ohaus', 'stuart'],
        'isitmasiz-manyetik-karistirici' => ['velp', 'weightlab', 'stuart'],
        'vorteks-karistiricilar' => ['velp', 'weightlab', 'stuart'],
        'jar-test' => ['velp'],
        'diger-cevre-cihazlari' => ['velp', 'weightlab'],
        'sogutmali-inkubator' => ['weightlab', 'stuart'],
        'boi-olcum-cihazi' => ['wtw', 'velp'],
        'hot-plate' => ['velp', 'weightlab', 'ohaus', 'stuart'],
        'rotator-calkalayici' => ['velp', 'weightlab', 'stuart'],
        'su-banyolari' => ['weightlab'],
        'su-banyosu' => ['weightlab'],
        'ultrasonik-banyo' => ['weightlab'],
        'santrifujler' => ['weightlab'],
        'inkubatorler' => ['weightlab', 'stuart'],
        'erime-noktasi' => ['stuart'],
        'polarimetreler' => ['bellingham-stanley'],
        'etuv' => ['weightlab'],
        'balon-isiticilar' => ['velp', 'weightlab'],
        'termoreaktor' => ['velp'],
        'homojenizator' => ['velp', 'weightlab'],
        'mekanik-karistirici' => ['velp', 'weightlab'],
        'manyetik-karistirici' => ['velp', 'weightlab'],
    ],

    'product_category_services' => [
        'teraziler' => ['kutle-terazi-kalibrasyonu'],
        'analitik-teraziler' => ['kutle-terazi-kalibrasyonu'],
        'hassas-teraziler' => ['kutle-terazi-kalibrasyonu'],
        'endustriyel-teraziler' => ['kutle-terazi-kalibrasyonu'],
        'mikro-teraziler' => ['kutle-terazi-kalibrasyonu'],
        'nem-tayin' => ['kutle-terazi-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'titratorler' => ['hacim-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'kral-fischer' => ['hacim-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'karl-fischer-titratorler' => ['hacim-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'kulometrik-karl-fischer-titratorler' => ['hacim-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'volumetrik-karl-fischer-titratorler' => ['hacim-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'potansiyometrik-titratorler' => ['hacim-kalibrasyonu'],
        'piston-buretler' => ['hacim-kalibrasyonu'],
        'fotometrik-olcum-elektrodu' => [],
        'metal-kombine-elektrodlar' => [],
        'referans-elektrodlar' => [],
        'sicaklik-olcum-elektrodlari' => ['sicaklik-kalibrasyonu'],
        'densitometre' => ['sicaklik-kalibrasyonu', 'hacim-kalibrasyonu'],
        'yogunluk-olcerler' => ['sicaklik-kalibrasyonu', 'hacim-kalibrasyonu'],
        'refraktometre' => ['sicaklik-kalibrasyonu'],
        'laboratuvar-tipi-refraktometreler' => ['sicaklik-kalibrasyonu'],
        'tasinabilir-tip-optik-refraktometreler' => [],
        'tasinabilir-tip-dijital-refraktometreler' => [],
        'ph-metre' => ['sicaklik-kalibrasyonu'],
        'cozunmus-oksijen-olcum-elektrodlari' => [],
        'iletkenlik-olcum-elektrodlari' => [],
        'iyon-secici-elektrodlar' => [],
        'kombine-ph-elektrodlari' => [],
        'elektrod-baglanti-kablolari' => [],
        'ph-iletkenlik' => ['sicaklik-kalibrasyonu'],
        'viskozimetre' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'rotasyonel-viskozimetre' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'tekstur-analiz-cihazi' => [],
        'karistiricilar' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'isitmali-manyetik-karistirici' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'isitmasiz-manyetik-karistirici' => ['devir-kalibrasyonu'],
        'vorteks-karistiricilar' => ['devir-kalibrasyonu'],
        'jar-test' => ['devir-kalibrasyonu'],
        'diger-cevre-cihazlari' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        'sogutmali-inkubator' => ['sicaklik-kalibrasyonu'],
        'boi-olcum-cihazi' => [],
        'hot-plate' => ['sicaklik-kalibrasyonu'],
        'rotator-calkalayici' => ['devir-kalibrasyonu'],
        'su-banyolari' => ['sicaklik-kalibrasyonu'],
        'su-banyosu' => ['sicaklik-kalibrasyonu'],
        'ultrasonik-banyo' => ['sicaklik-kalibrasyonu'],
        'santrifujler' => ['devir-kalibrasyonu'],
        'inkubatorler' => ['sicaklik-kalibrasyonu'],
        'erime-noktasi' => ['sicaklik-kalibrasyonu'],
        'polarimetreler' => [],
        'etuv' => ['sicaklik-kalibrasyonu'],
        'balon-isiticilar' => ['sicaklik-kalibrasyonu'],
        'termoreaktor' => ['sicaklik-kalibrasyonu'],
        'homojenizator' => ['devir-kalibrasyonu'],
        'mekanik-karistirici' => ['devir-kalibrasyonu'],
        'manyetik-karistirici' => ['devir-kalibrasyonu', 'sicaklik-kalibrasyonu'],
    ],

    'products' => [
        [
            'name' => 'A&D FZ-500i Hassas Terazi',
            'slug' => 'and-fz-500i-hassas-terazi',
            'category' => 'Teraziler',
            'category_slug' => 'teraziler',
            'brand' => 'A&D',
            'brand_slug' => 'and',
            'model' => 'FZ-500i',
            'sku' => 'MTA-AND-FZ500I',
            'seo_title' => 'A&D FZ-500i Hassas Terazi | MTA Endüstri',
            'meta_description' => 'A&D FZ-500i hassas terazi için teknik özellikler, kategori, marka ve teklif talebi bilgileri.',
            'summary' => '0.001 g hassasiyetli laboratuvar tartım süreçleri için hazırlanmış tek görselli katalog ürün örneği.',
            'image' => 'images/products/fz-500i-hassas-terazi-0-001-g.jpg',
            'image_alt' => 'A&D FZ-500i hassas terazi ürün fotoğrafı',
            'image_label' => 'A&D FZ-500i ürün görseli',
            'features' => ['Hassas tartım uygulamaları', 'Laboratuvar kullanımına uygun yapı', 'Teknik doküman alanı', 'Terazi kalibrasyonu ile ilişkilendirilebilir'],
            'metadata' => [
                'Marka' => 'A&D',
                'Kategori' => 'Teraziler',
                'Model' => 'FZ-500i',
                'SKU' => 'MTA-AND-FZ500I',
                'Kullanım alanı' => 'Laboratuvar tartım',
            ],
            'specs' => [
                'Kapasite' => '520 g',
                'Hassasiyet' => '0.001 g',
                'Kalibrasyon' => 'Harici kalibrasyon',
                'Ekran' => 'LCD',
            ],
            'documents' => ['Katalog PDF alanı', 'Datasheet alanı'],
            'related_services' => ['kutle-terazi-kalibrasyonu'],
        ],
        [
            'name' => 'Ohaus MB120 Nem Tayin Cihazı',
            'slug' => 'ohaus-mb120-nem-tayin-cihazi',
            'category' => 'Nem Tayin',
            'category_slug' => 'nem-tayin',
            'brand' => 'Ohaus',
            'brand_slug' => 'ohaus',
            'model' => 'MB120',
            'sku' => 'MTA-OH-MB120',
            'seo_title' => 'Ohaus MB120 Nem Tayin Cihazı | MTA Endüstri',
            'meta_description' => 'Ohaus MB120 nem tayin cihazı için teknik özellikler, marka ve kategori bilgileri.',
            'summary' => 'Numune nem oranı ölçümü için katalog yapısında hazırlanmış ürün örneği.',
            'image_label' => 'Ürün görseli alanı',
            'features' => ['Halojen ısıtma teknolojisi', 'Laboratuvar numune analizi', 'Tek ana ürün görseli', 'Teklif formu ile ilişkilendirme'],
            'metadata' => [
                'Marka' => 'Ohaus',
                'Kategori' => 'Nem Tayin',
                'Model' => 'MB120',
                'SKU' => 'MTA-OH-MB120',
                'Kullanım alanı' => 'Nem analizi',
            ],
            'specs' => [
                'Kapasite' => '120 g',
                'Okunabilirlik' => '0.001 g',
                'Isıtma tipi' => 'Halojen',
                'Uygulama' => 'Nem tayini',
            ],
            'documents' => ['Katalog PDF alanı', 'Kullanım kılavuzu alanı'],
            'related_services' => ['kutle-terazi-kalibrasyonu', 'sicaklik-kalibrasyonu'],
        ],
        [
            'name' => 'Kyoto KEM MKC-710 Kral Fischer Titratörü',
            'slug' => 'kyoto-kem-mkc-710-kral-fischer-titratoru',
            'category' => 'Kral Fischer',
            'category_slug' => 'kral-fischer',
            'brand' => 'Kyoto KEM',
            'brand_slug' => 'kyoto-kem',
            'model' => 'MKC-710',
            'sku' => 'MTA-KEM-MKC710',
            'seo_title' => 'Kyoto KEM MKC-710 Kral Fischer Titratörü | MTA Endüstri',
            'meta_description' => 'Kyoto KEM MKC-710 Karl Fischer titratörü için teknik özellikler, marka ve teklif talebi.',
            'summary' => 'Karl Fischer su tayini uygulamaları için teknik katalog ürün örneği.',
            'image' => 'images/products/mkc-710m-kral-fischer-1.jpg',
            'image_alt' => 'Kyoto KEM MKC-710 Kral Fischer titratörü ürün görseli',
            'image_label' => 'Ürün görseli alanı',
            'features' => ['Volumetrik su tayini uygulaması', 'Laboratuvar analiz süreçleri', 'Doküman yönetimi', 'Teklif odaklı ürün sayfası'],
            'metadata' => [
                'Marka' => 'Kyoto KEM',
                'Kategori' => 'Kral Fischer',
                'Model' => 'MKC-710',
                'SKU' => 'MTA-KEM-MKC710',
                'Kullanım alanı' => 'Su miktarı tayini',
            ],
            'specs' => [
                'Metot' => 'Karl Fischer titrasyonu',
                'Cihaz tipi' => 'Otomatik titratör',
                'Uygulama' => 'Su tayini',
                'Doküman' => 'Datasheet alanı',
            ],
            'documents' => ['Katalog PDF alanı', 'Aplikasyon notu alanı'],
            'related_services' => ['hacim-kalibrasyonu'],
        ],
        [
            'name' => 'WTW Multi 3630 IDS pH & İletkenlik Ölçer',
            'slug' => 'wtw-multi-3630-ids-ph-iletkenlik-olcer',
            'category' => 'pH & İletkenlik',
            'category_slug' => 'ph-iletkenlik',
            'brand' => 'WTW',
            'brand_slug' => 'wtw',
            'model' => 'Multi 3630 IDS',
            'sku' => 'MTA-WTW-3630',
            'seo_title' => 'WTW Multi 3630 IDS pH ve İletkenlik Ölçer | MTA Endüstri',
            'meta_description' => 'WTW Multi 3630 IDS pH ve iletkenlik ölçer için teknik katalog bilgileri.',
            'summary' => 'Saha ve laboratuvar ölçümleri için çok parametreli ölçüm cihazı örneği.',
            'image_label' => 'Ürün görseli alanı',
            'features' => ['pH ve iletkenlik ölçümü', 'Çok parametreli kullanım', 'Saha uygulamalarına uygun yapı', 'Teknik özellik tablosu'],
            'metadata' => [
                'Marka' => 'WTW',
                'Kategori' => 'pH & İletkenlik',
                'Model' => 'Multi 3630 IDS',
                'SKU' => 'MTA-WTW-3630',
                'Kullanım alanı' => 'Su analizi',
            ],
            'specs' => [
                'Parametreler' => 'pH, iletkenlik, sıcaklık',
                'Kullanım tipi' => 'Portatif',
                'Veri yönetimi' => 'Cihaz hafızası',
                'Uygulama' => 'Laboratuvar ve saha',
            ],
            'documents' => ['Katalog PDF alanı', 'Kullanım kılavuzu alanı'],
            'related_services' => ['sicaklik-kalibrasyonu'],
        ],
        [
            'name' => 'VELP AREX-6 Manyetik Karıştırıcı',
            'slug' => 'velp-arex-6-manyetik-karistirici',
            'category' => 'Manyetik Karıştırıcı',
            'category_slug' => 'manyetik-karistirici',
            'brand' => 'VELP',
            'brand_slug' => 'velp',
            'model' => 'AREX-6',
            'sku' => 'MTA-VELP-AREX6',
            'seo_title' => 'VELP AREX-6 Manyetik Karıştırıcı | MTA Endüstri',
            'meta_description' => 'VELP AREX-6 manyetik karıştırıcı için teknik özellikler, kategori ve marka bilgileri.',
            'summary' => 'Laboratuvar karıştırma ve ısıtmalı karıştırma uygulamaları için katalog ürünü.',
            'image' => 'images/products/velp-arex-6-digital-isitmali-manyetik-karistirici-1.jpg',
            'image_alt' => 'VELP AREX-6 manyetik karıştırıcı ürün görseli',
            'image_label' => 'Ürün görseli alanı',
            'features' => ['Manyetik karıştırma', 'Isıtmalı çalışma seçeneği', 'Laboratuvar kullanımına uygun yapı', 'Ürün görseli ve doküman alanı'],
            'metadata' => [
                'Marka' => 'VELP',
                'Kategori' => 'Manyetik Karıştırıcı',
                'Model' => 'AREX-6',
                'SKU' => 'MTA-VELP-AREX6',
                'Kullanım alanı' => 'Karıştırma ve ısıtma',
            ],
            'specs' => [
                'Karıştırma tipi' => 'Manyetik',
                'Uygulama' => 'Laboratuvar numune hazırlama',
                'Kontrol' => 'Hız ve sıcaklık kontrolü',
                'Doküman' => 'Datasheet alanı',
            ],
            'documents' => ['Katalog PDF alanı', 'Datasheet alanı'],
            'related_services' => ['sicaklik-kalibrasyonu'],
        ],
    ],

    'articles' => [
        [
            'title' => 'Basınç Kalibrasyonu Nedir?',
            'slug' => 'basinc-kalibrasyonu-nedir',
            'category' => 'Kalibrasyon Rehberleri',
            'category_slug' => 'kalibrasyon-rehberleri',
            'author' => 'MTA Teknik Editör',
            'reading_time' => '4 dk',
            'published_at' => '2026-08-26',
            'updated_at' => '2026-08-26',
            'excerpt' => 'Basınç kalibrasyonunun ne işe yaradığını, hangi cihazlarda kullanıldığını ve neden periyodik yapılması gerektiğini açıklayan giriş içeriği.',
            'answer' => 'Basınç kalibrasyonu, basınç ölçen bir cihazın gösterdiği değerin güvenilir bir referansla karşılaştırılması ve sonuçların raporlanmasıdır.',
        ],
        [
            'title' => 'Teknik Ürün Seçiminde Dikkat Edilecek Kriterler',
            'slug' => 'teknik-urun-seciminde-kriterler',
            'category' => 'Satın Alma Rehberleri',
            'category_slug' => 'satin-alma-rehberleri',
            'author' => 'MTA Teknik Editör',
            'reading_time' => '5 dk',
            'published_at' => '2026-08-26',
            'updated_at' => '2026-08-26',
            'excerpt' => 'Endüstriyel ölçüm ürünleri seçilirken teknik özellik, kullanım alanı, doküman ve servis ilişkilerinin nasıl değerlendirilmesi gerektiği.',
            'answer' => 'Teknik ürün seçiminde yalnızca ürün adı değil; ölçüm aralığı, doğruluk, ortam koşulları, servis ihtiyacı ve doküman desteği birlikte değerlendirilmelidir.',
        ],
        [
            'title' => 'Kalibrasyon Nedir?',
            'slug' => 'kalibrasyon-nedir',
            'category' => 'Kalibrasyon Rehberleri',
            'category_slug' => 'kalibrasyon-rehberleri',
            'author' => 'MTA Teknik Editör',
            'reading_time' => '6 dk',
            'published_at' => '2026-09-02',
            'updated_at' => '2026-09-02',
            'excerpt' => 'Kalibrasyon nedir, neden yapılır, hangi cihazlarda uygulanır, kalibrasyon ile ayar ve doğrulama arasındaki fark nedir ve kalibrasyon periyodu nasıl belirlenir?',
            'answer' => 'Kalibrasyon, bir ölçüm cihazının gösterdiği değerin izlenebilir bir referans ile karşılaştırılması, sapmanın belirlenmesi ve sonuçların belirsizlik bilgisiyle birlikte bir sertifikada raporlanması işlemidir.',
        ],
        [
            'title' => 'Kalibrasyon Sertifikası Nedir ve Neleri İçerir?',
            'slug' => 'kalibrasyon-sertifikasi',
            'category' => 'Kalibrasyon Rehberleri',
            'category_slug' => 'kalibrasyon-rehberleri',
            'author' => 'MTA Teknik Editör',
            'reading_time' => '5 dk',
            'published_at' => '2026-09-02',
            'updated_at' => '2026-09-02',
            'excerpt' => 'Kalibrasyon sertifikası (kalibrasyon raporu) nedir, hangi bilgileri içerir, TÜRKAK akredite sertifika ile akreditasyonsuz rapor arasındaki fark nedir ve geçerlilik süresi nasıl belirlenir?',
            'answer' => 'Kalibrasyon sertifikası; kalibre edilen cihazı, uygulanan yöntemi, ölçüm noktalarını, bulunan sapmaları ve genişletilmiş ölçüm belirsizliğini (k=2) izlenebilirlik bilgisiyle birlikte belgeleyen resmi rapordur.',
        ],
        [
            'title' => 'Analitik Terazi Nedir?',
            'slug' => 'analitik-terazi-nedir',
            'category' => 'Satın Alma Rehberleri',
            'category_slug' => 'satin-alma-rehberleri',
            'author' => 'MTA Teknik Editör',
            'reading_time' => '5 dk',
            'published_at' => '2026-09-02',
            'updated_at' => '2026-09-02',
            'excerpt' => 'Analitik terazi nedir, hassas teraziden farkı nedir, okunabilirlik ve kapasite değerleri ne anlama gelir, analitik terazi seçerken ve kurarken nelere dikkat edilir?',
            'answer' => 'Analitik terazi, tipik olarak 0,1 mg (0,0001 g) okunabilirliğe ve rüzgarlık kabinine sahip, düşük miktarlı numunelerin yüksek doğrulukla tartılması için kullanılan laboratuvar terazisidir.',
        ],
    ],

    'faqs' => [
        [
            'question' => 'Ürünler siteden satın alınabilecek mi?',
            'answer' => 'Hayır. Site ürünleri katalog mantığında gösterecek; ürün sayfaları teklif ve bilgi talebi üretmek için kullanılacak.',
        ],
        [
            'question' => 'Hizmet ve ürün içerikleri admin panelden yönetilecek mi?',
            'answer' => 'Evet. İkinci fazda Filament admin paneli ile hizmet, ürün, sayfa, SEO, FAQ ve lead yönetimi eklenecek.',
        ],
        [
            'question' => 'SEO alanları her sayfada düzenlenebilecek mi?',
            'answer' => 'Evet. Title, meta description, canonical, OG verileri ve schema seçenekleri admin tarafında yönetilebilir şekilde tasarlanacak.',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Yetkili / merkez servis anlaşmaları
    |--------------------------------------------------------------------------
    | Marka bazlı yetkili servis rozeti. Her kayıt hem top bar'da kısa link,
    | hem ilgili hizmet/teknik servis detay sayfasında öne çıkan blok üretir.
    | Yeni bir marka anlaşması eklemek için buraya bir satır eklemek yeterli.
    */
    'authorized_services' => [
        'bahco' => [
            'brand' => 'Bahco',
            'logo' => 'images/brands/bahco.png',
            'role' => 'Türkiye Yetkili Merkez Servisi',
            'short' => 'Bahco Yetkili Servis',
            'tagline' => 'Bahco tork anahtarları ve tork ürünleri için yetkili merkez servis',
            'blurb' => 'MTA Endüstri, Bahco tork anahtarları ve tork ürünleri için yetkili merkez servistir. '
                . 'Arıza tespiti, bakım, ayar ve kalibrasyon öncesi hazırlık işlemlerini üretici standartlarında yürütür; '
                . 'servis ve akredite tork kalibrasyonunu tek noktadan sunar.',
            'points' => [
                'Orijinal Bahco yedek parça ve komponent tedariki',
                'Üretici prosedürlerine uygun bakım, ayar ve kilitleme kontrolü',
                'Teknik servis + TÜRKAK akredite tork kalibrasyonu tek elden',
                'Kayıtlı servis geçmişi ve garanti takibi',
            ],
            // Hangi sayfalarda öne çıkacak (slug listeleri):
            'technical_service_slugs' => ['tork-anahtarlari-servisi'],
            'service_slugs' => ['tork-kalibrasyonu'],
            // Top bar linkinin gideceği hedef:
            'primary_target' => ['type' => 'technical_service', 'slug' => 'tork-anahtarlari-servisi'],
            'show_in_topbar' => true,
        ],
    ],
];
